# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
MLP TKG model configuration data

Config format: [vnc_degree, batch, seqlen, hidden, intermediate, dtype, quant_dtype, quant_type,
                tpbSgCyclesSum, norm_type, fused_add, store_add, act_fn_type, skip_gate_proj,
                gate_bias, up_bias, down_bias, norm_bias, use_tkg_gate_up_proj_column_tiling,
                use_tkg_down_proj_column_tiling, use_tkg_down_proj_optimized_layout]
"""

import nki.language as nl
from nkilib_src.nkilib.core.utils.common_types import ActFnType, NormType, QuantizationType

# fmt: off
# Format: [vnc, b, s, h, i, dt, q_dt, q_t, cycles, norm, fa, sa, act, skip, gb, ub, db, nb, gate_col, down_col, down_opt]
mlp_tkg_model_configs = [
    # ============ GEMMA3_27B CONFIGS ============
    [
        2,
        1,
        1,
        5376,
        336,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        2,
        1,
        5376,
        336,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        4,
        1,
        5376,
        336,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        8,
        1,
        5376,
        336,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        16,
        1,
        5376,
        336,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        1,
        1,
        5376,
        672,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        2,
        1,
        5376,
        672,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        4,
        1,
        5376,
        672,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        8,
        1,
        5376,
        672,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        16,
        1,
        5376,
        672,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        32,
        1,
        5376,
        672,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        2,
        1,
        5376,
        1344,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        4,
        1,
        5376,
        1344,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        8,
        1,
        5376,
        1344,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        16,
        1,
        5376,
        1344,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        32,
        1,
        5376,
        1344,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        64,
        1,
        5376,
        1344,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        128,
        1,
        5376,
        1344,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        2,
        256,
        1,
        5376,
        1344,
        nl.bfloat16,
        None,
        QuantizationType.NONE,
        0,
        NormType.RMS_NORM,
        False,
        False,
        ActFnType.SiLU,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    # ============ QWEN3_32B CONFIGS ============
    [2, 128, 1, 5120, 3200, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 5120, 3200, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 1, 5120, 3200, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2048, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 5120, 3200, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 5120, 3200, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 5120, 3200, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 5120, 3200, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2048, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4096, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 5120, 3200, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 5120, 3200, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 5120, 400, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 5120, 800, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 5120, 3200, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 1, 5120, 1600, nl.bfloat16, None, QuantizationType.NONE, 0, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    # llama3_70b
    [2, 1, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 5, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 5, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 5, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 5, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 1, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 5, 8192, 14336, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 5, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 5, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 5, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 5, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 5, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 5, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 5, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 5, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 1, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 1, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 5, 8192, 7168, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 5, 8192, 7168, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 5, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 5, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 5, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 5, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 5, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 5, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 5, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 5, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 1, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 1, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 5, 8192, 3584, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 2, 5, 8192, 3584, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 5, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 5, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 5, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 5, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 1, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 5, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 4, 5, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 1, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 5, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 32, 5, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 8192, 1792, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 256, 1, 8192, 1792, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 1, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 5, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 8, 5, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 1, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 5, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 64, 5, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 8192, 896, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 512, 1, 8192, 896, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 8192, 448, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 1, 8192, 448, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 448, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1, 5, 8192, 448, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 448, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 1, 8192, 448, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 448, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 16, 5, 8192, 448, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 448, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 1, 8192, 448, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 448, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 128, 5, 8192, 448, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 448, nl.bfloat16, nl.float8_e4m3, QuantizationType.STATIC, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
    [2, 1024, 1, 8192, 448, nl.bfloat16, None, QuantizationType.NONE, None, NormType.RMS_NORM, False, False, ActFnType.SiLU, False, False, False, False, False, True, True, False],
]
# fmt: on
