# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ty: ignore — vendored GPT-OSS test; golden/optional-arg idioms trip ty's type mapping
"""Multi-layer GPT-OSS decode "mega kernel" vs the HF golden, on hardware.

Stacks ``num_layers`` fused DP x TP attention + EP MoE decoder layers
(``gpt_oss_decode_mega_kernel``) and validates the whole stack directly against
the vendored HF-bit-validated whole-layer oracle ``gptoss_mxfp4_decode_layer``,
called ``num_layers`` times threading the hidden state (exactly
``GptOssModel.forward_decode``).

Identical to the real GPT-OSS-20B decode structure:
  * 32 experts, top-k 4  -> EP32, DP4 x TP8 (32 ranks, 1 expert/rank).
  * GQA: 64 Q-heads, 8 KV-heads (num_kv_groups=8). At TP8, rank r owns Q-heads
    [8r,8r+8) AND KV head r (clean 1:1 -> KV head r serves exactly rank r's Qs).
  * head_dim 64; hidden 2880 (kernel-padded to 3072, hidden_actual=2880);
    intermediate 2880 (padded to 3072); MXFP4 experts.
  * SWA-alternating: even layers slide (window 128), odd layers full attention.
  * Block (paged) KV cache, per layer.

Layer-chaining: each fused layer's output ``[B/(DP*TP), H]`` is the next layer's
input (same SP layout), so the kernel just loops the layer body threading ``x``;
per-layer weights + KV caches are passed as lists. The golden ref mirrors this by
looping the whole-layer oracle, threading the running hidden state and using each
layer's own weights, KV cache, and SWA setting.

The per-layer attention head-split (full 64Q/8KV == sum of per-rank (8Q + own KV
head) partials, O-proj bias once) and the MXFP4->dense adapter are CPU-proven; the
single-layer variant of this exact composition is HW-validated in
test_gpt_oss_decode_layer_dp_tp_ep_golden.py. This test adds the multi-layer
chaining, the GQA-8 sharding, real 20B dims, and SWA alternation.

MXFP4 experts -> TRN3 only.

Set ``VLLM_NEURON_MEGA_FULL_120B=1`` for the 36-layer DP16 x TP8 x EP128
profiling configuration. Combine it with ``VLLM_NEURON_MEGA_SKIP_GOLDEN=1`` and
``VLLM_NEURON_MEGA_SHARE_LAYER_INPUTS=1`` to reuse one copy of invariant
weights and KV caches across all layers. Set
``VLLM_NEURON_MEGA_INPUT_CACHE_DIR`` to persist generated per-rank inputs as
raw files; subsequent runs memory-map and hard-link them instead of regenerating
or rewriting them. Change ``VLLM_NEURON_MEGA_INPUT_CACHE_TAG`` to force a miss.
Set ``VLLM_NEURON_MEGA_FP8_KV=1`` to use the packed OCP-E4M3 KV-cache path.
"""

import inspect
import logging
import os

import nki.language as nl
import numpy as np
import pytest
import torch
from nki.collectives import ReplicaGroup

# The GIGA kernel (gpt_oss_decode_mega_kernel) is maintained as a self-contained,
# vendored package under src/.../c128-giga-kernel/ (generated by
# scripts/vendor_giga_kernel.py). The bootstrap import puts that folder on
# sys.path so this test exercises the standalone copy, not the in-tree module.
from nkilib_src.nkilib.models.gpt_oss.c128_giga_kernel.experimental.gpt_oss.gpt_oss_decode_layer_dp_tp_ep import (
    gpt_oss_decode_mega_kernel,
)

from test.integration.nkilib.core.moe_block.test_moe_block_tkg import generate_inputs
from test.integration.nkilib.experimental.transformer.test_attention_block_tkg import (
    generate_kernel_inputs,
)
from test.integration.nkilib.experimental.transformer.test_attention_block_tkg_utils import (
    AttnBlkTestConfig,
)
from test.utils.common_dataclasses import (
    CompilerArgs,
    CustomValidator,
    CustomValidatorWithOutputTensorData,
    InferenceArgs,
    NKICompilationMode,
    Platforms,
    TraceMode,
)
from test.utils.persistent_input_cache import PersistentPerRankInputCache, build_input_cache_key
from test.utils.pytest_parametrize import pytest_parametrize
from test.utils.pytest_test_metadata import pytest_marks, pytest_test_metadata
from test.utils.test_orchestrator import Orchestrator
from test.utils.unit_test_collective_framework import CollectiveUnitTestFramework

from .gptoss_mxfp4_golden import GptOssConfig, gptoss_mxfp4_decode_layer
from .gptoss_mxfp4_golden.kernels import attention_decode as _golden_attention_decode
from .mxfp4_dense_adapter import (
    packed_mx_to_dense_down,
    packed_mx_to_dense_gate_up,
    unpack_gate_up_bias,
)


def _env_enabled(name: str) -> bool:
    return os.environ.get(name, "0") not in ("", "0", "false", "False")


# Set to skip the (expensive) golden reference — the fused multi-layer golden runs
# the whole-layer HF oracle once per rank (32 ranks, sequential) at real 20B dims,
# which dominates wall time (~40 min at 8 layers). When set, the kernel still
# compiles, runs on device, and profiles; only the golden generation + numerical
# validation are skipped (via a zero-returning stub ref, so the harness output
# descriptors stay correct). Use for perf/profiling runs, NOT correctness runs.
_SKIP_GOLDEN = _env_enabled("VLLM_NEURON_MEGA_SKIP_GOLDEN")
_FULL_120B_PROFILE = _env_enabled("VLLM_NEURON_MEGA_FULL_120B")
_SHARE_LAYER_INPUTS = _env_enabled("VLLM_NEURON_MEGA_SHARE_LAYER_INPUTS")
_INPUT_CACHE_DIR = os.environ.get("VLLM_NEURON_MEGA_INPUT_CACHE_DIR", "").strip()
_INPUT_CACHE_TAG = os.environ.get("VLLM_NEURON_MEGA_INPUT_CACHE_TAG", "default")
_REUSE_INPUT_ARTIFACTS = os.environ.get("VLLM_NEURON_MEGA_REUSE_INPUT_ARTIFACTS", "").strip()

# Runtime env vars forwarded to every worker process (the harness passes only
# InferenceArgs.env_vars through; ambient env does not reach the workers).
# Format: "NAME=VALUE;;NAME2=VALUE2".
# Optional: ship a locally-built libnrt.so with the job and point the 128 workers at it via
# LD_LIBRARY_PATH. This is PROCESS-SCOPED -- the harness uploads the artifacts dir to a
# PID-unique /tmp path and LD_LIBRARY_PATH is per-process env, so /opt/aws/neuron/lib and every
# other user's job on the shared host are untouched (no dpkg, no shared-state mutation).
# Used to test the 128-peer mesh all_to_all descriptor-uniformity patch.
_EXTRA_LIB_DIR = os.environ.get("MEGA_EXTRA_LIB_DIR", "")

# Entries are ";;"-separated, so a VALUE that itself needs ";" (e.g.
# NEURON_RT_CC_ALG_TYPES_PER_STREAM="0:ALG;1:ALG") cannot be written literally -- it gets
# truncated at the first ";;"-split. Write "@" in the value and it is translated to ";" here.
_WORKER_ENV = {
    k: v.replace("@", ";")
    for k, v in (kv.split("=", 1) for kv in os.environ.get("MEGA_WORKER_ENV", "").split(";;") if "=" in kv)
}

# MEGA_EXTRA_LIB_DIR only STAGES the .so into the artifacts dir; nothing pointed the workers at
# it, so a locally built libnrt.so was uploaded and then ignored. Prepend the remote artifacts
# dir (cwd of the capture command) to LD_LIBRARY_PATH so the staged lib actually loads.
if _EXTRA_LIB_DIR:
    # LD_LIBRARY_PATH alone is NOT enough: /opt/aws/neuron/bin/neuron-explorer is linked with
    # RUNPATH=/opt/aws/neuron/lib, and RUNPATH is searched BEFORE LD_LIBRARY_PATH for a binary's
    # direct DT_NEEDED entries -- so the stock libnrt.so.1 always won and every "patched runtime"
    # run in this workspace silently used the stock library. LD_PRELOAD takes precedence over
    # both, so force the staged copy in explicitly.
    _WORKER_ENV["LD_LIBRARY_PATH"] = "$PWD:/opt/aws/neuron/lib"
    _WORKER_ENV["LD_PRELOAD"] = "$PWD/libnrt.so.1"

# Packed FP8 KV uses the OCP E4M3 dtype so it can coexist with the OCP MXFP4
# expert weights in one NEFF. K is packed as two FP8 rows per storage row;
# V remains in the ordinary FP8 block layout.
_FP8_KV = _env_enabled("VLLM_NEURON_MEGA_FP8_KV")
_KV_QUANT_DTYPE = nl.float8_e4m3fn

# KV CACHE UPDATE (VLLM_NEURON_MEGA_KV_UPDATE=1): the kernel writes each decode token's K/V
# back into the paged cache in-place and returns (x, K_cache, V_cache); the harness aliases
# those onto the K_cache/V_cache input buffers (create_inputs uses *.must_alias_input keys) and
# the golden compares the post-update caches. Requires stacked per-layer caches (each layer
# writes its own K_cache[li] slice), so it is INCOMPATIBLE with SHARE_LAYER_INPUTS.
#
# PROFILING REPRESENTATIVENESS: a KV-update profile is only representative with weight sharing
# DISABLED (VLLM_NEURON_MEGA_SHARE_LAYER_INPUTS unset -> layer_input_count == num_layers). With
# sharing on, all layers reuse one weight/cache tensor, so the compiler skips per-layer weight
# re-load DMA that a real decode pays; that also makes the caches unstackable (see above). To
# A/B the KV-write cost against a read-only baseline, run BOTH with sharing off so the only
# difference is the write -- otherwise the DMA delta is dominated by the layer_input_count 1<->36
# weight-reload change, not the KV update.
_KV_UPDATE = _env_enabled("VLLM_NEURON_MEGA_KV_UPDATE")

# ── Real GPT-OSS-20B decode structure (kernel-padded dims). ──
_TP = 8
_H = 3072  # hidden, padded from 2880 to a multiple of 512 for the MX kernel
_H_ACTUAL = 2880  # true 20B hidden (RMSNorm divisor)
_I = 3072  # intermediate, padded from 2880
_D_HEAD = 64
_Q_HEADS = 8  # Q-heads per rank (TP8 head shard); full model = 64
_KV_HEADS = 1  # KV-heads per rank; full model = 8 (GQA, 1 per rank at TP8)
_FULL_Q_HEADS = _TP * _Q_HEADS  # 64
_FULL_KV_HEADS = _TP * _KV_HEADS  # 8
# The profiling default is 10k. Override this for smaller correctness runs.
_S_CTX = int(os.environ.get("VLLM_NEURON_MEGA_S_CTX", "10240"))
_S_TKG = 1
_TOP_K = 4
_EPS = 1e-5
_SWIGLU_ALPHA = 1.702
_GATE_CLAMP_UPPER = 7.0
_UP_CLAMP_UPPER = 8.0
_UP_CLAMP_LOWER = -6.0
_BLOCK_LEN = 128  # block (page) size; matches the production decode configuration
_SLIDING_WINDOW = 128  # real 20B SWA window (even layers)
_P_MAX = 128  # attention kernel partition-tile size (S_ctx must be a multiple)
_MX = nl.float4_e2m1fn_x4
_DTYPE = nl.float16

# The default is GPT-OSS-20B. Full-scale profiling uses the GPT-OSS-120B
# topology previously exercised by the optimization commits.
_DP = 16 if _FULL_120B_PROFILE else 4
_N_EXPERTS = 128 if _FULL_120B_PROFILE else 32
_RANKS = 128 if _FULL_120B_PROFILE else 32
_MOE_SEED = 1234  # global np.random seed set right before generate_inputs so its
# gen_moe_mx_weights (which runs before generate_inputs' own
# np.random.seed(42)) is reproducible across kernel + ref.

# (num_layers, logical_nc_config)
LAYER_PARAM_NAMES = "num_layers, logical_nc_config"
LAYER_PARAMS = [(36, 1)] if _FULL_120B_PROFILE else [(1, 1), (2, 1), (4, 1), (8, 1)]
_ABBREVS = {"num_layers": "L", "logical_nc_config": "lnc"}


def _is_sliding(layer_idx: int) -> bool:
    """Real GPT-OSS: even layers slide, odd layers are full attention."""
    return layer_idx % 2 == 0


def _num_swa_blocks(sliding_window, block_len, num_full_blocks):
    """Number of KV blocks a sliding layer's TRIMMED block table needs.

    Mirrors the production model runner ``_compute_swa_num_blocks``: the window
    needs ``sliding_window // block_len + 1`` blocks, rounded UP to a multiple of
    ``_P_MAX // block_len`` (so the trimmed S_ctx stays a multiple of the
    attention kernel's P_MAX tile), then clipped to the full-context block count.
    At block_len 128 / window 128 this is 2 blocks (trimmed S_ctx = 256) vs the
    full 80 blocks (S_ctx 10240).
    """
    min_blocks = sliding_window // block_len + 1
    blocks_per_pmax = max(1, _P_MAX // block_len)
    rounded = (min_blocks + blocks_per_pmax - 1) // blocks_per_pmax * blocks_per_pmax
    return int(min(rounded, num_full_blocks))


def _trim_block_table_and_positions(btab, pos_ids, sliding_window, block_len):
    """Trim a FULL per-rank block table + absolute positions into the SWA window
    frame, exactly like the production ``_compute_swa_decode_tensors``.

    Args:
        btab: full block table ``[B, num_full_blocks]`` (kv_heads==1 form; LOCAL
            block indices, -1 sentinels for inactive blocks).
        pos_ids: absolute positions ``[B, S_tkg]`` (== per-seq cache_len for S_tkg=1).
        sliding_window: SWA window (>0).
        block_len: block (page) size.

    Returns:
        (trimmed_btab ``[B, num_swa]``, pos_ids_swa ``[B, S_tkg]``), where the
        trimmed table gathers the window-relevant blocks
        ``[start_block, start_block + num_swa)`` per seq and ``pos_ids_swa`` is
        ``pos_ids - start_block * block_len`` (position in the trimmed frame).
        Reading the trimmed table with the shifted positions yields bit-identical
        attention to reading the full table with absolute positions (proven), but
        touches only ``num_swa`` blocks of HBM.
    """
    B, num_full = btab.shape
    num_swa = _num_swa_blocks(sliding_window, block_len, num_full)
    # Per-seq window start block from the active position (min over S_tkg == the
    # single decode token here). clamp>=0 for short sequences.
    pos = pos_ids.astype(np.int64)
    min_pos = pos.min(axis=1)  # [B]
    start_block = np.clip(min_pos // block_len - num_swa + 1, 0, None)  # [B]
    gather_idx = start_block[:, None] + np.arange(num_swa, dtype=np.int64)[None, :]  # [B, num_swa]
    trimmed = np.take_along_axis(btab, gather_idx.astype(btab.dtype), axis=1)
    pos_swa = (pos - (start_block * block_len)[:, None]).astype(np.float32)
    return np.ascontiguousarray(trimmed.astype(np.int32)), np.ascontiguousarray(pos_swa)


def _localize_update_idx(upd, block_len, kv_heads):
    """Map GLOBAL block-KV update slots to this rank's LOCAL single-KV-head slots.

    ``generate_kernel_inputs`` builds ``kv_cache_update_idx`` against the flattened
    ``num_blocks * kv_heads`` pool: the physical slot is
    ``(base * kv_heads + head) * block_len + offset``. But each rank owns only its OWN
    single-KV-head cache ``[nb, 1, block_len, d]`` indexed ``0..nb-1`` — exactly the
    localization the block TABLE already gets (``abt_head // kv_heads``). The update
    index must get the SAME localization, otherwise it addresses ``~kv_heads x`` out of
    bounds: every scatter is then skipped (kernel ``oob_mode.skip``) or clamped to the
    last slot (golden), so the KV write is never actually exercised in-bounds (and the
    fp8 gather-modify-scatter desyncs ranks -> collective hang). Recover
    ``base = global_block // kv_heads`` (head-independent, 0<=head<kv_heads) and rebuild
    ``base * block_len + offset``. The uint32 sentinel (0xFFFFFFFF, intentionally-padded
    tokens) is preserved so those tokens still skip.

    Args:
        upd: global block-KV update index (uint32), any shape; value =
            (base*kv_heads+head)*block_len + offset, or 0xFFFFFFFF for padding.
        block_len: block (page) size.
        kv_heads: full-model KV-head count folded into the global pool (GQA fan-out).

    Returns:
        uint32 array (same shape) of local single-head slots (base*block_len+offset),
        sentinels preserved.

    Example:
        >>> _localize_update_idx(np.array([(5*8+3)*128 + 7], np.uint32), 128, 8)
        array([647], dtype=uint32)  # base=5 -> 5*128+7
    """
    u = np.asarray(upd).astype(np.int64)
    sentinel = u >= int(np.iinfo(np.uint32).max)  # 0xFFFFFFFF padding
    local = ((u // block_len) // kv_heads) * block_len + (u % block_len)
    return np.where(sentinel, np.int64(0xFFFFFFFF), local).astype(np.uint32)


def _attn_cfg_full(batch, sliding_window):
    """ONE coherent full-model (64Q/8KV GQA) attention set for a DP replica.

    All TP ranks in a replica share the KV heads / cache / tokens / cos / sin /
    mask; each rank slices its own 8-Q-head + KV-head-r shard. sliding_window>0
    for even (SWA) layers, 0 for odd (full) layers.
    """
    return AttnBlkTestConfig(
        batch=batch,
        q_heads=_FULL_Q_HEADS,
        kv_heads=_FULL_KV_HEADS,
        d_head=_D_HEAD,
        H=_H,
        H_actual=_H_ACTUAL,
        S_ctx=_S_CTX,
        S_max_ctx=_S_CTX,
        S_tkg=_S_TKG,
        lnc=1,
        block_len=_BLOCK_LEN,
        rmsnorm_X=True,
        test_sink=True,
        use_pos_id=True,
        sliding_window=sliding_window,
        update_cache=_KV_UPDATE,
        dtype=_DTYPE,
        kv_quant=_FP8_KV,
        kv_quant_dtype=_KV_QUANT_DTYPE,
        # PACKED FP8 for both read-only profiling AND KV UPDATE. The packed in-kernel WRITE
        # (_update_block_cache_vectorized -> _k_update_fp8_packed parity-split load-modify-store)
        # was previously believed to hang the inter-rank collective watchdog, so KV-update forced
        # UNPACKED. That hang was actually a FAULTY (out-of-bounds) kv_cache_update_idx desyncing
        # ranks (now fixed by _localize_update_idx); it manifested in BOTH packed and unpacked
        # layouts. With the index localized, the packed write is exercised in-bounds. The golden is
        # packed-aware (unpacks the 5D K on read, repacks the 6D stacked K on write), so packed KV
        # update is validated end-to-end here.
        fp8_packed=_FP8_KV,
    )


def _np_dtype():
    """numpy dtype matching the kernel stream dtype (_DTYPE = nl.float16)."""
    return np.float16


def _zero_attn_hidden_padding(aki):
    """Zero the padded hidden columns [H_actual:H] of the O-projection weight, in
    place, so attention writes 0 (not garbage) into the padded output columns.

    Real GPT-OSS 20B has hidden 2880; the LNC=1 MXFP4 kernel needs H%512==0 so we
    pad to 3072. ``generate_kernel_inputs`` already zeros the padded INPUT columns
    (X[:, H_actual:]=0) but leaves W_out's padded output columns [:, H_actual:]
    random. Those feed the residual stream and the next layer's MoE, and the
    kernel's MXFP4 path can overflow them to +/-inf, which then mismatches the
    dense fp32 golden (finite garbage) as a finite-vs-inf error even though the
    real 2880 columns agree. Zeroing W_out's padded output columns makes both the
    kernel and the (locally-regenerated) golden emit 0 there, so the full-tensor
    comparison passes and we validate the true 2880-wide result. Called on the
    SAME regenerated ``aki`` in both create_inputs and the golden ref, so they stay
    bit-identical.
    """
    Wout = np.asarray(aki["W_out"])  # [q_heads*d_head, H]
    if Wout.shape[1] > _H_ACTUAL:
        Wout[:, _H_ACTUAL:] = 0
    return aki


# Memoized attention-input generation. The full 64Q/8KV attention set (aki) is a
# pure function of (seed, sliding_window, B_attn): generate_array_inputs and the
# golden ref both build it as _zero_attn_hidden_padding(generate_kernel_inputs(
# _attn_cfg_full(B_attn, sliding), seed=seed)), with seed = 1000*dp_replica +
# 31*layer. So only DP*layer_input_count distinct akis exist, yet the harness
# regenerates them per rank in the cross-rank consistency check, the eager ref-input
# build, AND the golden compute. generate_kernel_inputs is the single largest golden
# cost (~1-2 s/call at these dims). Memoizing on the key collapses that to one build
# per distinct aki. The cached aki is treated as read-only: every consumer copies
# before mutating (slice / np.ascontiguousarray / _to_t / .clone()), and
# _zero_attn_hidden_padding is idempotent, so sharing one instance across ranks is
# bit-safe. The memo is a module global so a parent process's fills are inherited
# copy-on-write by ranks the SimDistRunner forks (see make_golden_ref's priming).
_ATTN_AKI_MEMO = {}


def _gen_attn_inputs(seed, sliding, batch):
    """Return the (memoized) full-model attention input set for this (seed, sliding,
    batch). Byte-identical to the previous inline
    ``_zero_attn_hidden_padding(generate_kernel_inputs(_attn_cfg_full(batch, sliding),
    seed=seed))`` — it just caches the result so repeated (seed, sliding) across
    ranks reuse one build."""
    key = (seed, sliding, batch)
    aki = _ATTN_AKI_MEMO.get(key)
    if aki is None:
        aki = _zero_attn_hidden_padding(generate_kernel_inputs(_attn_cfg_full(batch, sliding), seed=seed))
        _ATTN_AKI_MEMO[key] = aki
    return aki


def _zero_moe_hidden_padding(mg):
    """Zero the padded hidden-output columns [H_actual:H] of the MoE down projection
    (packed weight, its scale, and the down bias), in place. The down projection's
    last axis IS the hidden output H (packed down weight [E,128,n_I512,H], scale
    [E,16,n_I512,H], bias [E,H]); its padded columns are random and would land
    random values in the layer's padded output columns (differently for the kernel's
    MXFP4 path vs the dense golden). Zeroing them makes both emit 0 there so the
    full-tensor comparison validates only the real 2880-wide result. Applied to the
    same weight set create_inputs slices from AND the ref regenerates, keeping them
    identical."""
    for key, hax in (("expert_down_weights", -1), ("expert_down_weights_scale", -1), ("expert_down_bias", -1)):
        a = np.asarray(mg[key])
        if a.shape[hax] > _H_ACTUAL:
            a[..., _H_ACTUAL:] = 0
    return mg


def _regen_moe_global():
    """Return the global MXFP4->dense MoE weight set (identical across layers AND
    ranks: ``generate_inputs`` seeds internally, so every layer's ``create_inputs``
    MoE slice comes from the same weights). Generation (~33s at H=I=3072, 32 experts)
    + dense dequant (~6s) dominate the golden cost and are recomputed identically by
    all 32 ranks (each in its own process), so the result is DISK-MEMOIZED: the first
    rank builds + pickles it, the rest load it. Cost becomes O(1) across ranks+layers
    instead of O(ranks * layers)."""
    import os
    import pickle
    import tempfile

    cache = os.path.join(tempfile.gettempdir(), f"gptoss_mega_moe_dense_H{_H}_I{_I}_E{_N_EXPERTS}.pkl")
    if os.path.exists(cache):
        try:
            with open(cache, "rb") as f:
                return pickle.load(f)
        except Exception:
            pass  # corrupt/partial -> rebuild
    # CRITICAL determinism: generate_inputs calls gen_moe_mx_weights (which draws
    # from GLOBAL np.random) BEFORE its own np.random.seed(42), so the MXFP4 expert
    # weights depend on the global RNG state at call time. create_inputs (kernel side)
    # and this ref must seed identically right before the call so both get the SAME
    # weights, else the golden compares against different experts (cosine ~0.16).
    np.random.seed(_MOE_SEED)
    mg = generate_inputs(
        batch=_RANKS,
        seqlen=1,
        hidden=_H,
        hidden_actual=_H_ACTUAL,
        intermediate=_I,
        num_global_experts=_N_EXPERTS,
        num_local_experts=_N_EXPERTS,
        top_k=_TOP_K,
        router_fn=None,
        hidden_act_fn=None,
        expert_affinities_scaling_mode=None,
        moe_weight_dtype=_MX,
        input_dtype=_DTYPE,
        has_bias=True,
        has_clamp=True,
        router_act_first=False,
        norm_topk_prob=False,
        skip_router_logits=True,
        router_mm_dtype=nl.float16,
        is_all_expert=True,
    )
    mg["expert_gate_up_bias"][:, :, 1, ...] += 1.0  # GPT-OSS +1 on up bias
    _zero_moe_hidden_padding(mg)  # zero padded H output cols
    dense = {
        "gu": packed_mx_to_dense_gate_up(mg["expert_gate_up_weights"], mg["expert_gate_up_weights_scale"], _H, _I),
        "dn": packed_mx_to_dense_down(mg["expert_down_weights"], mg["expert_down_weights_scale"], _H, _I),
        "gub": unpack_gate_up_bias(mg["expert_gate_up_bias"], _H, _I),
        "dnb": _to_t(mg["expert_down_bias"]),
        "router_w": _to_t(mg["router_weights"]).t().contiguous(),
        "router_b": _to_t(mg["router_bias"]).reshape(-1),
        "gamma": _to_t(mg["gamma"]).reshape(_H),
    }
    try:
        tmp = cache + f".{os.getpid()}.tmp"
        with open(tmp, "wb") as f:
            pickle.dump(dense, f, protocol=pickle.HIGHEST_PROTOCOL)
        os.replace(tmp, cache)
    except Exception:
        pass  # cache is best-effort
    return dense


def _to_t(a):
    if a is None:
        return None
    if isinstance(a, torch.Tensor):
        return a.float()
    s = str(a.dtype)
    if "bfloat16" in s or "float8" in s or "float16" in s:
        return torch.from_numpy(a.astype(np.float32))
    if a.dtype == np.uint32:
        return torch.from_numpy(a.astype(np.int64))
    return torch.from_numpy(a.copy())


def make_golden_ref(tp_group, ep_group, tp_size, ep_size, num_layers):
    """Golden-backed distributed ref: loop the whole-layer oracle num_layers times.

    Threads the hidden state layer-to-layer (== GptOssModel.forward_decode); each
    layer rebuilds its full 64Q/8KV attention weights + KV cache via AllGather[TP]
    and its full expert set via AllGather[EP], then calls gptoss_mxfp4_decode_layer
    with that layer's own SWA setting. Returns this rank's SP token shard.
    """

    # Per-DP-replica ``out_full`` cache (see ref's memo note). Keyed by dp_replica.
    _outfull_memo = {}

    def _compute_out_full(
        dp_replica,
        B_attn,
        S_tkg,
        num_layers,
        top_k,
        eps,
        gate_clamp_upper_limit,
        cos,
        sin,
        pos_ids,
        pos_ids_swa,
        active_blocks_table,
        active_blocks_table_swa,
    ):
        """Run the num_layers whole-layer oracle stack for a whole DP replica and
        return the full ``out_full`` [B_attn, H]. This is the exact per-rank layer
        loop the ref used to run inline — factored out so it runs ONCE per replica
        instead of once per TP rank. The shared attention control (cos/sin/pos/block
        tables) is TP-rank-invariant, so passing the caller's copies is exact."""
        H = _H
        I = _I
        d_head = _D_HEAD

        # Shared attention control. Full (odd) layers use the absolute positions +
        # full block table; sliding (even) layers use the SAME shared trimmed table
        # + window-frame positions the kernel uses (passed as kernel inputs), so the
        # golden reads the identical physical blocks / logical span the kernel does.
        cos_g = _to_t(cos).permute(1, 2, 0).reshape(B_attn * S_tkg, d_head // 2)
        sin_g = _to_t(sin).permute(1, 2, 0).reshape(B_attn * S_tkg, d_head // 2)
        pos_flat = _to_t(pos_ids).reshape(-1).long()  # absolute (full layers)
        pos_flat_swa = _to_t(pos_ids_swa).reshape(-1).long()  # window frame (sliding layers)
        # Shared full / trimmed block tables (kv_heads==1 local form: [B, nb]).
        btab_full_shared = _to_t(active_blocks_table).reshape(B_attn, -1).int()
        btab_swa_shared = _to_t(active_blocks_table_swa).reshape(B_attn, -1).int()
        # KV UPDATE: the golden oracle writes this token's K/V in-place into the bound cache at
        # slot_mapping. Use the SAME physical slot the kernel writes (kv_cache_update_idx, which
        # is physical_block*block_len + offset), and DON'T clone, so the reference cache carries
        # the update. Without KV update the write is discarded (slot=0, cache cloned) as before.
        # Collected post-update per-layer full caches [nb, kv_heads, block_len, d] (kv_heads=8).
        # Per-layer ingredients for ref's per-rank single-head cache-update reproduction.
        kv_upd_ingredients = {} if _KV_UPDATE else None
        slot = torch.zeros(B_attn * S_tkg, dtype=torch.long)  # read-only path only (write discarded)

        # Full MoE dense weight set (identical for every layer; built + dequantized
        # ONCE — the expensive generate_inputs (~33s) and dequant (~6s) are hoisted
        # out of the per-layer loop so cost is O(1) in num_layers, not O(L)).
        moe_dense = _regen_moe_global()

        # Running hidden state: replica's B_attn pre-norm tokens (regenerated at
        # layer 0 from the same seed create_inputs used; identical on every TP rank).
        hidden = None
        for li in range(num_layers):
            sliding = _SLIDING_WINDOW if _is_sliding(li) else 0
            aki = _gen_attn_inputs(1000 * dp_replica + 31 * li, sliding, B_attn)
            if li == 0:
                hidden = _to_t(aki["X"]).reshape(B_attn, H)

            # Full 64Q/8KV attention weights + KV cache (no reassembly needed).
            Wqkv = _to_t(aki["W_qkv"])
            Wout = _to_t(aki["W_out"])
            sink_g = _to_t(aki["sink"]).reshape(-1)
            Kc, Vc = _to_t(aki["K_cache"]), _to_t(aki["V_cache"])  # [nb, 8, block_len, d]
            iln_w = _to_t(aki["rmsnorm_X_gamma"]).reshape(H)
            if _FP8_KV:
                k_scale_scalar = float(_to_t(aki["k_scale"]).float().flatten()[0])
                v_scale_scalar = float(_to_t(aki["v_scale"]).float().flatten()[0])
                # Packed K is [nb, kv, block_len//2, d, 2]. Restore the logical
                # block axis before feeding the dense golden.
                if Kc.dim() == 5:
                    nb, kv_heads, half_block, d_head, packed = Kc.shape
                    Kc = Kc.permute(0, 1, 2, 4, 3).reshape(nb, kv_heads, half_block * packed, d_head)
                Kc = Kc.float() / k_scale_scalar
                Vc = Vc.float() / v_scale_scalar
                # Input generation divides W_out by v_scale for the raw-FP8
                # kernel path. Undo that transform for the dense golden.
                Wout = Wout.float() * v_scale_scalar
            bqkv = torch.zeros(Wqkv.shape[1])  # test_bias=False -> no bias
            bout = torch.zeros(H)

            # SWA block-table trimming (mirror the kernel exactly; see the mega
            # kernel docstring). Sliding (even) layers read the SAME shared trimmed
            # table + window-frame positions the kernel reads, so the golden gathers
            # the identical window blocks of this layer's own KV cache; full (odd)
            # layers read the full table + absolute positions. Because the oracle is
            # trim-invariant (the stored K carries absolute-position RoPE, so
            # relabelling positions into the trimmed frame is exact), this matches
            # the pre-trim golden numerically while faithfully modelling the reduced
            # KV span. The full/trimmed tables and positions are layer-invariant here
            # (decode reuses layer 0's), so the shared kernel inputs are reused.
            if _is_sliding(li):
                layer_btab = btab_swa_shared
                layer_pos = pos_flat_swa
                sw = _SLIDING_WINDOW
            else:
                layer_btab = btab_full_shared
                layer_pos = pos_flat
                sw = None

            # This layer's full expert set (identical across layers; pre-dequantized).
            all_gu, all_dn = moe_dense["gu"], moe_dense["dn"]
            all_gub, all_dnb = moe_dense["gub"], moe_dense["dnb"]
            router_w, router_b = moe_dense["router_w"], moe_dense["router_b"]
            paln_w = moe_dense["gamma"]

            cfg = GptOssConfig(
                hidden_size=H,
                intermediate_size=I,
                num_attention_heads=_FULL_Q_HEADS,
                num_key_value_heads=_FULL_KV_HEADS,
                head_dim=d_head,
                num_local_experts=ep_size,
                num_experts_per_tok=top_k,
                rms_norm_eps=eps,
                swiglu_limit=gate_clamp_upper_limit,
                swiglu_alpha=_SWIGLU_ALPHA,
                torch_dtype=torch.float32,
                sliding_window=(_SLIDING_WINDOW if sw is not None else None),
            )
            out_full = gptoss_mxfp4_decode_layer(
                cfg,
                hidden_states=hidden,
                positions=layer_pos,
                cos=cos_g,
                sin=sin_g,
                input_layernorm_weight=iln_w,
                qkv_proj_weight=Wqkv,
                qkv_proj_bias=bqkv,
                o_proj_weight=Wout,
                o_proj_bias=bout,
                sinks=sink_g,
                post_attention_layernorm_weight=paln_w,
                router_weight=router_w,
                router_bias=router_b,
                gate_up_weight=all_gu,
                gate_up_bias=all_gub,
                down_weight=all_dn,
                down_bias=all_dnb,
                k_cache=Kc.clone(),
                v_cache=Vc.clone(),
                block_table=layer_btab,
                slot_mapping=slot,
                sliding_window=sw,
            ).to(torch.float32)  # [B_attn, H]

            if _KV_UPDATE:
                # Stash the per-layer ingredients ref needs to reproduce THIS rank's single-KV-head
                # cache write with the validated attention_decode primitive (num_kv_heads=1, so its
                # per-token slot write matches the kernel exactly — no per-head-slot ambiguity).
                # Positions: full (odd) layers use absolute; sliding (even) use the window frame.
                # The KV-write oracle (_golden_attention_decode) does a RAW X @ W_qkv with NO input
                # RMSNorm, but the kernel's attention_block_tkg has rmsnorm_X_enabled=True (normalizes
                # before QKV). So pre-apply this layer's input RMSNorm to the threaded hidden here and
                # stash the NORMED state, so the oracle's K/V matches the kernel's written K/V. Formula
                # matches moe_block_tkg's RMSNorm (fp32 accum, gamma scale).
                _xin = hidden.to(torch.float32)
                _var = _xin.pow(2).mean(-1, keepdim=True)
                _xnormed = (_xin * torch.rsqrt(_var + eps)) * iln_w.to(torch.float32)
                kv_upd_ingredients[li] = {
                    # THREADED, INPUT-NORMED hidden == the actual attention-QKV input for THIS layer
                    # (== the kernel's post-AllGather + input-RMSNorm state). MUST derive from `hidden`
                    # (the residual stream from the previous layer), NOT aki["X"]: the kernel computes
                    # each layer's K/V from the threaded state, so layer>=1's cache write depends on it.
                    # (For li==0 hidden==aki["X"].) `hidden` is still this layer's input here — it's
                    # rebound to out_full only after the stash. Cast back to the compute dtype.
                    "X": _xnormed.to(hidden.dtype).reshape(B_attn, H),
                    # Wqkv/Wout here are already in DEQUANT space for fp8 (Wout *= v_scale above),
                    # so attention_decode's fp16 write produces dequantized new K/V; ref re-quantizes.
                    "Wqkv": Wqkv,
                    "sink": sink_g,
                    "Wout": Wout,
                    "bout": torch.zeros(H),
                    # K0/V0 are the kernel's RAW cache: fp16 [nb,8,bl,d] normally, or packed-fp8
                    # (K [nb,8,bl//2,d,2], V [nb,8,bl,d]) when _FP8_KV. Kept in kernel storage form.
                    "K0": np.ascontiguousarray(aki["K_cache"]),
                    "V0": np.ascontiguousarray(aki["V_cache"]),
                    # NOTE: this layer's own GLOBAL kv_cache_update_idx is intentionally NOT stashed;
                    # the write slot is the SHARED, LOCALIZED layer-0 index (kv_cache_update_idx param)
                    # the kernel uses for every layer. See the slot_r assignment in ref().
                    "btab": layer_btab,
                    "pos": layer_pos,
                    "cos": cos_g,
                    "sin": sin_g,
                    "sw": sw,
                    "k_scale": (k_scale_scalar if _FP8_KV else None),
                    "v_scale": (v_scale_scalar if _FP8_KV else None),
                }

            # Thread the FULL layer output as the next layer's input (identical on
            # every TP rank in the replica). No collectives needed.
            hidden = out_full

        if _KV_UPDATE:
            return out_full, kv_upd_ingredients
        return out_full

    def ref(
        x_shard,
        input_layernorm_weight,
        W_qkv,
        bias_qkv,
        W_out,
        bias_out,
        sink,
        K_cache,
        V_cache,
        post_attn_layernorm_weight,
        router_weights,
        router_bias,
        expert_gate_up_weights,
        expert_down_weights,
        expert_gate_up_weights_scale,
        expert_down_weights_scale,
        expert_gate_up_bias,
        expert_down_bias,
        swa_start_pos_ids,
        cos,
        sin,
        active_blocks_table,
        active_blocks_table_swa,
        attention_mask,
        kv_cache_update_idx,
        pos_ids,
        pos_ids_swa,
        rank_id,
        tp_replica_group,
        ep_replica_group,
        num_layers,
        tp_size,
        ep_size,
        B_attn,
        S_tkg,
        top_k,
        eps,
        hidden_actual,
        softmax_scale,
        gate_clamp_upper_limit,
        up_clamp_upper_limit,
        up_clamp_lower_limit,
        k_scale=None,
        v_scale=None,
    ):
        # NOTE: the golden ref uses NO torch.distributed collectives. The
        # SimDistRunner golden harness caps a distributed ref at MAX_COLLECTIVE_PASSES
        # (=10) total collectives, which a multi-layer ref (>=~12/layer) blows past
        # -> deadlock. Instead each rank REGENERATES the full per-(layer, DP-replica)
        # inputs locally from the same deterministic seed create_inputs used
        # (seed = 1000*dp_replica + 31*li for attention; the shared global MoE set),
        # so it needs no gathers. The full 64Q/8KV weights, KV cache, and 32-expert
        # set are reconstructed directly; the whole-layer oracle then runs the full
        # layer over the replica's B_attn tokens and we slice this rank's token.
        dtype = x_shard.dtype
        T_shard, H = x_shard.shape
        rid = int(rank_id[0, 0])
        tp_rank = rid % tp_size
        dp_replica = rid // tp_size

        # The whole-layer forward output ``out_full`` [B_attn, H] depends only on
        # (dp_replica, num_layers): every TP rank in a replica regenerates identical
        # inputs (attention seed = 1000*dp_replica + 31*li, shared MoE set) and
        # computes the identical ``out_full`` — each rank only differs in which token
        # row it slices at the end. So compute it ONCE per replica and memoize; the
        # other 7 TP ranks of the replica reuse it. Verified bit-identical across TP
        # ranks and across separate forked processes. The memo is a closure dict so a
        # parent process's fills (see ``prime`` below) are inherited copy-on-write by
        # the ranks SimDistRunner forks, avoiding recompute in every child.
        memo = _outfull_memo.get(dp_replica)
        if memo is None:
            memo = _compute_out_full(
                dp_replica,
                B_attn,
                S_tkg,
                num_layers,
                top_k,
                eps,
                gate_clamp_upper_limit,
                cos,
                sin,
                pos_ids,
                pos_ids_swa,
                active_blocks_table,
                active_blocks_table_swa,
            )
            _outfull_memo[dp_replica] = memo
        # _compute_out_full returns (out_full, {li: ingredients}) under KV_UPDATE, else out_full.
        if _KV_UPDATE:
            out_full, upd_k = memo
        else:
            out_full = memo

        # This rank's own token: its TP position within the replica.
        out = out_full[tp_rank * T_shard : (tp_rank + 1) * T_shard, :].contiguous()
        result = {"out": out.numpy().astype(dtype)}

        if _KV_UPDATE:
            # Per-rank post-update cache, reproduced with the SAME validated attention_decode
            # primitive the kernel mirrors, run for THIS rank's single KV head (num_kv_heads=1).
            # That makes _write_kv_cache's per-token slot write unambiguous and matches the kernel's
            # per-rank single-KV-head cache [nb, 1, bl, d]; stacked over layers -> [L, nb, 1, bl, d],
            # exactly the K_cache input layout. Uses upd_k[li] ingredients (full-model tensors);
            # W_qkv/W_out/sink/cache/slot are sliced to this rank here (mirrors generate_array_inputs).
            qd_r = _Q_HEADS * _D_HEAD
            q_all = _FULL_Q_HEADS * _D_HEAD
            kv1 = _D_HEAD
            kbase, vbase = q_all, q_all + _FULL_KV_HEADS * _D_HEAD
            k_layers, v_layers = [], []
            for li in range(num_layers):
                ing = upd_k[li]
                Wqkv_f = ing["Wqkv"]  # [H, 64D + 2*8D]
                Wqkv_r = torch.cat(
                    [
                        Wqkv_f[:, tp_rank * qd_r : (tp_rank + 1) * qd_r],
                        Wqkv_f[:, kbase + tp_rank * kv1 : kbase + (tp_rank + 1) * kv1],
                        Wqkv_f[:, vbase + tp_rank * kv1 : vbase + (tp_rank + 1) * kv1],
                    ],
                    dim=1,
                ).contiguous()
                Wout_r = ing["Wout"][tp_rank * qd_r : (tp_rank + 1) * qd_r, :].contiguous()
                sink_r = ing["sink"].reshape(-1)[tp_rank * _Q_HEADS : (tp_rank + 1) * _Q_HEADS].contiguous()
                # This rank's single KV head, in kernel storage form.
                K0_r = ing["K0"][:, tp_rank : tp_rank + 1]  # fp16 [nb,1,bl,d] OR packed-fp8 [nb,1,bl//2,d,2]
                V0_r = ing["V0"][:, tp_rank : tp_rank + 1]  # fp16/fp8 [nb,1,bl,d]
                if _FP8_KV:
                    # Unpack K [nb,1,bl//2,d,2]->[nb,1,bl,d] and DEQUANT both to the float space the
                    # write compute uses (Wout already carries v_scale, so the written K/V come out
                    # dequantized). attention_decode's _write_kv_cache casts to the passed cache dtype,
                    # so give it float caches, then re-quantize+pack below to the kernel's stored form.
                    ksc, vsc = ing["k_scale"], ing["v_scale"]
                    # ml_dtypes.float8_e4m3fn arrays can't go through torch.from_numpy; cast to
                    # float32 in numpy first (dequant is exact for fp8-representable values).
                    Kt = torch.from_numpy(np.ascontiguousarray(K0_r).astype(np.float32))
                    if Kt.dim() == 5:  # [nb,1,bl//2,d,2] -> [nb,1,bl,d]
                        nb_, _kv, hb, dd, pk = Kt.shape
                        Kt = Kt.permute(0, 1, 2, 4, 3).reshape(nb_, _kv, hb * pk, dd)
                    Kc_r = Kt / ksc
                    Vc_r = torch.from_numpy(np.ascontiguousarray(V0_r).astype(np.float32)) / vsc
                else:
                    Kc_r = torch.from_numpy(np.ascontiguousarray(K0_r))  # fp16 [nb,1,bl,d]
                    Vc_r = torch.from_numpy(np.ascontiguousarray(V0_r))
                # Write slot: use the SHARED, LOCALIZED layer-0 update index the KERNEL uses for
                # EVERY layer (kv_cache_update_idx param == upd0, already [B, S_tkg] and localized to
                # this rank's single-head cache via _localize_update_idx; tp_rank-invariant). The
                # kernel takes ONE kv_cache_update_idx for all layers, so the golden must too — using
                # each layer's own global ing["upd"] here would both mis-slot (global vs local) and
                # diverge from the kernel's shared index. btab/pos below are likewise shared layer-0
                # derived (localized), keeping the golden write bit-consistent with the kernel.
                slot_r = torch.from_numpy(np.ascontiguousarray(kv_cache_update_idx).reshape(-1)).long()
                btab = ing["btab"]
                # abt for this rank: local block indices (strip the *8 head factor; keep -1 sentinels).
                abt_r = torch.where(btab < 0, btab, btab // _FULL_KV_HEADS).int()
                _golden_attention_decode(
                    X=ing["X"].reshape(B_attn, S_tkg, H),
                    W_qkv=Wqkv_r,
                    bias_qkv=torch.zeros(Wqkv_r.shape[1]),
                    num_q_heads=_Q_HEADS,
                    num_kv_heads=_KV_HEADS,
                    head_dim=_D_HEAD,
                    cos=ing["cos"],
                    sin=ing["sin"],
                    K_cache=Kc_r,
                    V_cache=Vc_r,
                    block_table=abt_r,
                    slot_mapping=slot_r,
                    pos_ids=ing["pos"].reshape(-1).long(),
                    sliding_window=ing["sw"],
                    sink=sink_r,
                    softmax_scale=softmax_scale,
                    W_out=Wout_r,
                    bias_out=ing["bout"],
                    update_cache=True,
                )  # Kc_r/Vc_r mutated in place (dequant space for fp8, native for fp16)
                if _FP8_KV:
                    # Re-quantize to fp8 (mirror attention_block_tkg_torch._quantize_kv_to_fp8).
                    # PACKED fp8 KV update: K_cache is the 6D stacked packed layout
                    # [L,nb,1,bl//2,d,2], so repack this layer's written K [nb,1,bl,d] ->
                    # [nb,1,bl//2,d,2] below (interleave adjacent pairs into the trailing dim).
                    ksc, vsc = ing["k_scale"], ing["v_scale"]
                    fp8_max = 448.0  # float8_e4m3fn max positive
                    Kq = torch.clamp(Kc_r * ksc, -fp8_max, fp8_max)  # [nb,1,bl,d]
                    Vq = torch.clamp(Vc_r * vsc, -fp8_max, fp8_max)
                    if K_cache.ndim == 6:  # stacked packed [L,nb,1,bl//2,d,2] -> repack per layer
                        nb_, _kv, bl_, dd = Kq.shape
                        Kq = Kq.reshape(nb_, _kv, bl_ // 2, 2, dd).permute(0, 1, 2, 4, 3)
                    k_layers.append(Kq.numpy())
                    v_layers.append(Vq.numpy())
                else:
                    k_layers.append(Kc_r.numpy())
                    v_layers.append(Vc_r.numpy())
            result["K_cache"] = np.stack(k_layers, axis=0).astype(K_cache.dtype)  # [L, nb, 1, bl(/2..), d(,2)]
            result["V_cache"] = np.stack(v_layers, axis=0).astype(V_cache.dtype)
        return result

    def prime(create_inputs_fn):
        """Populate ``_outfull_memo`` in the CURRENT (parent) process, before the
        SimDistRunner forks per-rank workers. Runs the whole-layer stack once per DP
        replica (rank ``dp*tp_size``); the forked ranks then inherit these results
        copy-on-write and every rank's ref() is a memo hit (just a token slice). This
        turns the golden compute from ranks full forwards into DP. Without this
        priming, each forked rank starts with an empty memo and would recompute its
        replica, so the sharing MUST happen in the parent. Uses torch threads<=4
        (verified bit-identical to the threads=1 result; forked ranks pin threads=1)."""
        import torch as _torch

        _saved = _torch.get_num_threads()
        _torch.set_num_threads(min(4, _saved))
        try:
            for dp in range(ep_size // tp_size):
                rank = dp * tp_size
                raw = create_inputs_fn(rank_id=rank)
                # Strip any ".must_alias_input" suffix (KV_UPDATE renames K_cache/V_cache) so the
                # ref's plain K_cache/V_cache params are populated, mirroring filter_ref_input.
                raw = {k.rsplit(".must_alias_input", 1)[0]: v for k, v in raw.items()}
                kwargs = {k: raw[k] for k in _REF_PARAM_NAMES if k in raw}
                ref(**kwargs)  # fills _outfull_memo[dp]
        finally:
            _torch.set_num_threads(_saved)

    ref.prime = prime
    return ref


# Parameter names of make_golden_ref's ``ref`` — used to filter create_inputs'
# (superset) output down to the ref signature when priming (see ref.prime). The
# optional k_scale/v_scale are included so the FP8-KV path passes them through.
_REF_PARAM_NAMES = (
    "x_shard",
    "input_layernorm_weight",
    "W_qkv",
    "bias_qkv",
    "W_out",
    "bias_out",
    "sink",
    "K_cache",
    "V_cache",
    "post_attn_layernorm_weight",
    "router_weights",
    "router_bias",
    "expert_gate_up_weights",
    "expert_down_weights",
    "expert_gate_up_weights_scale",
    "expert_down_weights_scale",
    "expert_gate_up_bias",
    "expert_down_bias",
    "swa_start_pos_ids",
    "cos",
    "sin",
    "active_blocks_table",
    "active_blocks_table_swa",
    "attention_mask",
    "kv_cache_update_idx",
    "pos_ids",
    "pos_ids_swa",
    "rank_id",
    "tp_replica_group",
    "ep_replica_group",
    "num_layers",
    "tp_size",
    "ep_size",
    "B_attn",
    "S_tkg",
    "top_k",
    "eps",
    "hidden_actual",
    "softmax_scale",
    "gate_clamp_upper_limit",
    "up_clamp_upper_limit",
    "up_clamp_lower_limit",
    "k_scale",
    "v_scale",
)


def make_stub_ref():
    """Zero-returning stand-in for the golden ref, used when VLLM_NEURON_MEGA_SKIP_GOLDEN
    is set. Same signature/output shape as make_golden_ref's ``ref`` so the harness's
    output descriptors are correct, but does NO weight regeneration / oracle math —
    the ~40-min golden pass becomes instant. Validation against this stub is
    meaningless (all zeros); use only for on-device perf/profiling runs.
    """

    def ref(
        x_shard,
        input_layernorm_weight,
        W_qkv,
        bias_qkv,
        W_out,
        bias_out,
        sink,
        K_cache,
        V_cache,
        post_attn_layernorm_weight,
        router_weights,
        router_bias,
        expert_gate_up_weights,
        expert_down_weights,
        expert_gate_up_weights_scale,
        expert_down_weights_scale,
        expert_gate_up_bias,
        expert_down_bias,
        swa_start_pos_ids,
        cos,
        sin,
        active_blocks_table,
        active_blocks_table_swa,
        attention_mask,
        kv_cache_update_idx,
        pos_ids,
        pos_ids_swa,
        rank_id,
        tp_replica_group,
        ep_replica_group,
        num_layers,
        tp_size,
        ep_size,
        B_attn,
        S_tkg,
        top_k,
        eps,
        hidden_actual,
        softmax_scale,
        gate_clamp_upper_limit,
        up_clamp_upper_limit,
        up_clamp_lower_limit,
        k_scale=None,
        v_scale=None,
    ):
        T_shard, H = x_shard.shape
        res = {"out": np.zeros((T_shard, H), dtype=x_shard.dtype)}
        if _KV_UPDATE:
            # output_keys includes K_cache/V_cache under KV_UPDATE; return matching-shape zeros
            # (validation is meaningless under skip-golden anyway).
            res["K_cache"] = np.zeros_like(np.asarray(K_cache))
            res["V_cache"] = np.zeros_like(np.asarray(V_cache))
        return res

    return ref


# Per-rank acceptance on the real 2880 hidden cols. Cosine is the PRIMARY gate
# (direction of the token's output vector); rel-L2 is a loose magnitude sanity
# bound. Most ranks land cos>=0.999 / rel<=0.05 (MXFP4 quant noise). A few tokens
# (~3/32 at 2 layers) sit near a router top-k boundary and flip to a different
# expert set in the MXFP4 kernel vs the dense fp32 golden -> still cos~0.94 (same
# direction) but rel-L2 up to ~0.38 for that one token. That is a real, expected
# MXFP4-vs-dense routing effect at the quant boundary (not a kernel bug), so the
# rel-L2 bound is set to admit it while cosine still guarantees the output is not
# garbage/orthogonal. Matches the repo's MX-MoE cosine-first validation convention.
_COS_MIN = 0.90  # cosine-similarity floor (primary correctness gate)
_REL_L2_MAX = 0.45  # relative-L2 ceiling (loose; admits single-token router flips)


def _make_cosine_validator(golden_out):
    """Per-rank validator: compare only the real (unpadded) hidden columns via
    cosine similarity + relative-L2, not strict elementwise allclose.

    Rationale (repo MX-MoE convention): the fused kernel is MXFP4 with in-matmul
    mxfp8 activation quant; the dense fp32 golden does not model that. Across
    stacked layers, a token whose layer-1 output lands near a router top-k boundary
    can pick a different expert set in the kernel vs the golden, changing many of
    that token's output columns — a real MXFP4-boundary effect, not a kernel bug.
    Strict per-element rel-diff explodes on those tokens (and on near-zero outputs),
    so we validate direction (cosine) + aggregate magnitude (rel-L2) on the real
    2880 columns, exactly as the repo's MX MoE / FP8-KV tests do.
    """
    g = np.asarray(golden_out)
    _gdtype = g.dtype
    _gshape = g.shape

    class _Cos(CustomValidator):
        def validate(self, actual):
            # The framework hands `actual` as a raw byte view; reinterpret it as the
            # golden's dtype/shape (same pattern as make_cosine_similarity_validator).
            av = np.asarray(actual)
            try:
                av = av.view(_gdtype).reshape(_gshape)
            except (ValueError, TypeError):
                pass
            a = av.reshape(-1).astype(np.float64)
            b = g.reshape(-1).astype(np.float64)
            n = min(a.shape[0], b.shape[0], _H_ACTUAL)  # real (unpadded) hidden cols
            a, b = a[:n], b[:n]
            cos = float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-12))
            rel = float(np.linalg.norm(a - b) / (np.linalg.norm(b) + 1e-12))
            ok = (cos >= _COS_MIN) and (rel <= _REL_L2_MAX)
            self._print_with_log(
                f"[mega cosine-validate] cosine={cos:.6f} (min {_COS_MIN}) "
                f"relative_L2={rel:.4f} (max {_REL_L2_MAX}) -> {'PASS' if ok else 'FAIL'}"
            )
            return ok

    return CustomValidatorWithOutputTensorData(validator=_Cos, output_ndarray=g)


def _cosine_comparator(rank_id, golden_dict):
    """run_test custom_comparator: wrap each output key's golden in the cosine
    validator so the framework validates via cosine+relL2 on the real 2880 cols."""
    return {k: _make_cosine_validator(v) for k, v in golden_dict.items()}


def _make_passthrough_validator(golden_out):
    """Accept-all validator (VLLM_NEURON_MEGA_SKIP_GOLDEN): validate() always True.
    Paired with the zero stub ref so device run + profiling proceed without a real
    golden. Does NOT check correctness."""
    g = np.asarray(golden_out)

    class _Pass(CustomValidator):
        def validate(self, actual):
            self._print_with_log("[mega skip-golden] validation SKIPPED (perf/profile run)")
            return True

    return CustomValidatorWithOutputTensorData(validator=_Pass, output_ndarray=g)


def _passthrough_comparator(rank_id, golden_dict):
    return {k: _make_passthrough_validator(v) for k, v in golden_dict.items()}


@pytest_test_metadata(
    name="GPT-OSS-120B multi-layer mega decode profile"
    if _FULL_120B_PROFILE
    else "GPT-OSS-20B multi-layer mega decode vs golden"
)
@pytest_marks(["collectives"])
@pytest.mark.high_rank
@pytest.mark.skip_simulation
class TestGptOssMegaDecodeGolden:
    """Multi-layer GPT-OSS decode with DP/TP/EP collectives, GQA, SWA, and block KV."""

    # Not marked @pytest.mark.fast: the multi-layer mega decode exceeds the release
    # precommit's 3000 MB compile memory-limit. Runs on shared fleet instead.
    @pytest_parametrize(LAYER_PARAM_NAMES, LAYER_PARAMS, abbrevs=_ABBREVS)
    def test_mega_decode_vs_golden(
        self,
        test_manager: Orchestrator,
        platform_target: Platforms,
        num_layers: int,
        logical_nc_config: int,
    ):
        if not platform_target.is_trn3():
            pytest.skip("MXFP4 (float4_e2m1fn_x4) is only supported on TRN3.")
        if _FULL_120B_PROFILE and not _SKIP_GOLDEN:
            pytest.fail("VLLM_NEURON_MEGA_FULL_120B requires VLLM_NEURON_MEGA_SKIP_GOLDEN=1")
        if _SHARE_LAYER_INPUTS and not _SKIP_GOLDEN:
            pytest.fail("VLLM_NEURON_MEGA_SHARE_LAYER_INPUTS is only valid with skip-golden profiling")
        if _REUSE_INPUT_ARTIFACTS and not _SKIP_GOLDEN:
            pytest.fail("VLLM_NEURON_MEGA_REUSE_INPUT_ARTIFACTS is only valid with skip-golden profiling")

        tp_subgroups = [list(range(d * _TP, (d + 1) * _TP)) for d in range(_DP)]
        tp_group = ReplicaGroup(tp_subgroups)
        ep_group = ReplicaGroup([list(range(_RANKS))])
        # Tokens per rank. NOTE: raising this does NOT reduce per-layer latency -- T_ep = T_shard *
        # RANKS, so the EP collective payloads grow linearly with it (RS-EP 20.3 -> 32.9 -> 58.2 us
        # modelled for T_shard 1/2/4) while matmul efficiency improves only sublinearly. It lowers
        # cost PER TOKEN (27.9 -> 20.3 -> 16.5 us of CC per token), i.e. it is a THROUGHPUT lever,
        # not a latency one. Left env-tunable for throughput studies.
        T_shard = int(os.environ.get("VLLM_NEURON_MEGA_T_SHARD", "1"))
        B_g = T_shard * _RANKS  # global tokens
        B_attn = T_shard * _TP  # 8 tokens/DP replica
        softmax_scale = float(_D_HEAD**-0.5)
        layer_input_count = 1 if _SHARE_LAYER_INPUTS else num_layers

        input_cache = None
        if _INPUT_CACHE_DIR:
            source_files = [
                source
                for source in (
                    __file__,
                    inspect.getsourcefile(generate_inputs),
                    inspect.getsourcefile(generate_kernel_inputs),
                )
                if source is not None
            ]
            cache_key = build_input_cache_key(
                {
                    "tag": _INPUT_CACHE_TAG,
                    "num_layers": num_layers,
                    "layer_input_count": layer_input_count,
                    "logical_nc_config": logical_nc_config,
                    "dp": _DP,
                    "tp": _TP,
                    "ranks": _RANKS,
                    "experts": _N_EXPERTS,
                    "hidden": _H,
                    "hidden_actual": _H_ACTUAL,
                    "intermediate": _I,
                    "head_dim": _D_HEAD,
                    "q_heads_per_rank": _Q_HEADS,
                    "kv_heads_per_rank": _KV_HEADS,
                    "context": _S_CTX,
                    "block_len": _BLOCK_LEN,
                    "sliding_window": _SLIDING_WINDOW,
                    "moe_seed": _MOE_SEED,
                    # T_shard sets B_attn, so it changes every per-rank input shape. Omitting it
                    # made a T_shard=2 run silently load the T_shard=1 cache and die at trace with
                    # "cannot reshape tensor of size 8 (shape (8,1)) into shape (1,16)".
                    "t_shard": T_shard,
                    "fp8_kv": _FP8_KV,
                    "kv_quant_dtype": str(_KV_QUANT_DTYPE) if _FP8_KV else None,
                },
                source_files,
            )
            input_cache = PersistentPerRankInputCache(_INPUT_CACHE_DIR, cache_key)
            logging.info("GPT-OSS mega input cache namespace: %s", input_cache.directory)

        # Per-layer global MXFP4 MoE weight sets (E=_N_EXPERTS, sliced per rank).
        # generate_inputs seeds internally (np.random.seed(42)), so the MoE weights
        # are identical across layers; that is fine for a correctness test (the
        # golden ref uses the same per-layer weights). The default correctness mode
        # still gives layers distinct attention inputs; shared-input profiling
        # intentionally reuses layer 0's tensors while preserving all 36 executions.
        # MoE weights are identical across layers (generate_inputs is seeded); build
        # ONCE and reuse. Keep this lazy so a complete persistent-cache hit never
        # generates the large global expert set.
        mg_shared = None

        def get_moe_inputs():
            nonlocal mg_shared
            if mg_shared is None:
                # Seed immediately before generation so this matches
                # _regen_moe_global. MXFP4 generation draws from the global RNG
                # before generate_inputs applies its internal seed.
                np.random.seed(_MOE_SEED)
                mg_shared = generate_inputs(
                    batch=B_g,
                    seqlen=1,
                    hidden=_H,
                    hidden_actual=_H_ACTUAL,
                    intermediate=_I,
                    num_global_experts=_N_EXPERTS,
                    num_local_experts=_N_EXPERTS,
                    top_k=_TOP_K,
                    router_fn=None,
                    hidden_act_fn=None,
                    expert_affinities_scaling_mode=None,
                    moe_weight_dtype=_MX,
                    input_dtype=_DTYPE,
                    has_bias=True,
                    has_clamp=True,
                    router_act_first=False,
                    norm_topk_prob=False,
                    skip_router_logits=True,
                    router_mm_dtype=nl.float16,
                    is_all_expert=True,
                )
                mg_shared["expert_gate_up_bias"][:, :, 1, ...] += 1.0
                _zero_moe_hidden_padding(mg_shared)
            return mg_shared

        def generate_array_inputs(rank_id: int):
            nonlocal mg_shared
            dp_replica = rank_id // _TP
            tp_rank = rank_id % _TP
            e = rank_id  # this rank's global expert index (EP)
            qd_r = _Q_HEADS * _D_HEAD
            q_all = _FULL_Q_HEADS * _D_HEAD
            kv1 = _D_HEAD  # cols per single KV head
            moe_inputs = get_moe_inputs()

            # Per-layer lists.
            (iln, wqkv, bqkv, wout, bout, sink, kcache, vcache, paln, rw, rb, egu, edn, egus, edns, egub, edb, swa) = (
                [] for _ in range(18)
            )
            for li in range(layer_input_count):
                sliding = _SLIDING_WINDOW if _is_sliding(li) else 0
                # Seed per (layer, replica) so layers/replicas are distinct but all
                # TP ranks in a replica share the SAME full attention set. Memoized on
                # (seed, sliding, B_attn) so the 8 TP ranks of a replica reuse one build.
                aki = _gen_attn_inputs(1000 * dp_replica + 31 * li, sliding, B_attn)

                X_full = aki["X"].reshape(B_attn, _H)
                if li == 0:
                    x_shard = X_full[tp_rank * T_shard : (tp_rank + 1) * T_shard].copy()

                # W_qkv: this rank's 8 Q-head cols + its KV-head-r K/V cols.
                Wqkv_full = aki["W_qkv"]  # [H, 64*D + 2*(8*D)]
                kbase = q_all
                vbase = q_all + _FULL_KV_HEADS * _D_HEAD
                Wqkv_r = np.ascontiguousarray(
                    np.concatenate(
                        [
                            Wqkv_full[:, tp_rank * qd_r : (tp_rank + 1) * qd_r],
                            Wqkv_full[:, kbase + tp_rank * kv1 : kbase + (tp_rank + 1) * kv1],
                            Wqkv_full[:, vbase + tp_rank * kv1 : vbase + (tp_rank + 1) * kv1],
                        ],
                        axis=1,
                    )
                )
                Wout_r = np.ascontiguousarray(aki["W_out"][tp_rank * qd_r : (tp_rank + 1) * qd_r, :])
                sink_r = np.ascontiguousarray(aki["sink"][tp_rank * _Q_HEADS : (tp_rank + 1) * _Q_HEADS, :])
                # Packed FP8 K has one extra trailing dimension. Slice only the
                # KV-head axis so both packed and ordinary layouts are accepted.
                Kc_full, Vc_full = aki["K_cache"], aki["V_cache"]
                Kc_r = np.ascontiguousarray(Kc_full[:, tp_rank : tp_rank + 1])
                Vc_r = np.ascontiguousarray(Vc_full[:, tp_rank : tp_rank + 1, :, :])
                # active_blocks_table: [B, 8, num_blocks] holds GLOBAL block indices
                # into the flattened num_blocks*kv_heads pool (value = base*8 + head).
                # This rank gets its OWN single-KV-head cache [nb, 1, bl, d] indexed
                # 0..nb-1, so its table must carry LOCAL block indices (base), not the
                # head-shifted global ones -> divide out the *8 head factor (keep -1
                # sentinels). Then feed as a [B, num_blocks] table (kv_heads==1 form).
                abt_full = aki["active_blocks_table"]  # [B, 8, num_blocks]
                abt_head = abt_full[:, tp_rank, :]  # [B, num_blocks], values base*8+tp_rank
                abt_r = np.ascontiguousarray(np.where(abt_head < 0, abt_head, abt_head // _FULL_KV_HEADS))
                mask_full = aki["attention_mask"]  # [S_tkg-ish, B, 64, S_tkg] head-broadcast
                mask_r = np.ascontiguousarray(mask_full[:, :, tp_rank * _Q_HEADS : (tp_rank + 1) * _Q_HEADS, :])
                # kv_cache_update_idx: [B, kv_heads, S_tkg] for kv_heads>1 -> this rank's head.
                # With update_cache=True the block-KV write path expects the kv_heads==1 form
                # [B, S_tkg] (physical slot per token), so squeeze the singleton kv-head axis;
                # the read-only path (update off) keeps the 3D [B, 1, S_tkg] shape it validated with.
                # CRITICAL (KV UPDATE): the generated slot is GLOBAL — (base*kv_heads+head)*block_len
                # + offset into the flattened num_blocks*kv_heads pool. This rank's cache is the OWN
                # single-KV-head [nb, 1, bl, d] indexed 0..nb-1 (the block TABLE above is localized by
                # //kv_heads), so the write slot MUST be localized the SAME way, else it addresses
                # ~kv_heads x out of bounds and every scatter is skipped/clamped (write never runs
                # in-bounds; fp8 gather-modify-scatter desyncs ranks -> collective hang).
                upd_full = aki["kv_cache_update_idx"]
                if upd_full.ndim == 3:
                    upd_r = np.ascontiguousarray(upd_full[:, tp_rank : tp_rank + 1, :])
                    if _KV_UPDATE:
                        upd_r = np.ascontiguousarray(upd_r[:, 0, :])  # [B, S_tkg]
                        upd_r = _localize_update_idx(upd_r, _BLOCK_LEN, _FULL_KV_HEADS)
                else:
                    upd_r = upd_full
                # bias_qkv/bias_out are None here (test_bias=False). Can't stack None,
                # and the kernel expects a real tensor per layer -> pass zeros (zero
                # bias == no bias; the ref also uses zeros, so it's exact).
                qkv_cols = _Q_HEADS * _D_HEAD + 2 * _KV_HEADS * _D_HEAD
                bqkv_r = np.zeros((1, qkv_cols), dtype=np.float32).astype(_np_dtype())
                bout_r = np.zeros((1, _H), dtype=np.float32).astype(_np_dtype())

                iln.append(aki["rmsnorm_X_gamma"])
                wqkv.append(Wqkv_r)
                bqkv.append(bqkv_r)
                wout.append(Wout_r)
                bout.append(bout_r)
                sink.append(sink_r)
                kcache.append(Kc_r)
                vcache.append(Vc_r)
                mg = moe_inputs
                paln.append(mg["gamma"])
                rw.append(mg["router_weights"])
                rb.append(mg["router_bias"])
                egu.append(mg["expert_gate_up_weights"][e : e + 1])
                edn.append(mg["expert_down_weights"][e : e + 1])
                egus.append(mg["expert_gate_up_weights_scale"][e : e + 1])
                edns.append(mg["expert_down_weights_scale"][e : e + 1])
                egub.append(mg["expert_gate_up_bias"][e : e + 1])
                edb.append(mg["expert_down_bias"][e : e + 1])
                # Shared (layer-invariant) attention control taken from layer 0.
                if li == 0:
                    cos0, sin0 = aki["cos"], aki["sin"]
                    abt0, mask0, upd0, pos0 = abt_r, mask_r, upd_r, aki["pos_ids"]
                    if _FP8_KV:
                        k_scale0 = np.ascontiguousarray(aki["k_scale"])
                        v_scale0 = np.ascontiguousarray(aki["v_scale"])

            # SWA block-table trimming (matches production decode; see the mega
            # kernel docstring). Sliding (even) layers read only the window's blocks:
            # trim the shared full table + shift the shared positions into the window
            # frame. Both the kernel and the golden ref use these SAME shared trimmed
            # tensors for sliding layers, so they read identical physical blocks of
            # each layer's own KV cache -> bit-consistent, while touching only
            # ``num_swa`` blocks (2 at block_len 128 / window 128) instead of nbf (80).
            abt0_swa, pos0_swa = _trim_block_table_and_positions(
                np.asarray(abt0), np.asarray(pos0).astype(np.int64), _SLIDING_WINDOW, _BLOCK_LEN
            )
            # Per-layer SWA window start, expressed in the frame each layer uses.
            # This remains a small num_layers stack even when large tensors share
            # one leading-axis entry, because sliding and full layers differ.
            #  * sliding (even) layer -> trimmed frame: clamp(pos_swa - window + 1, 0)
            #  * full   (odd)  layer -> zeros (start 0 == full causal; ignored, the
            #    full path passes swa_start_pos_ids=0 as before).
            _start_swa = np.clip(pos0_swa - _SLIDING_WINDOW + 1, 0, None).astype(np.float32)
            _zero_start = np.zeros((B_attn, _S_TKG), dtype=np.float32)
            swa = [np.ascontiguousarray(_start_swa if _is_sliding(li) else _zero_start) for li in range(num_layers)]

            def _stack(lst):
                return np.ascontiguousarray(np.stack(lst, axis=0))

            arrays = {
                "x_shard": x_shard,
                # Per-layer weights STACKED on a leading layer axis (NKI rejects
                # list kernel args; HBM integer-index removes dim 0 -> layer i).
                "input_layernorm_weight": _stack(iln),
                "W_qkv": _stack(wqkv),
                "bias_qkv": _stack(bqkv),
                "W_out": _stack(wout),
                "bias_out": _stack(bout),
                "sink": _stack(sink),
                "K_cache": _stack(kcache),
                "V_cache": _stack(vcache),
                "post_attn_layernorm_weight": _stack(paln),
                "router_weights": _stack(rw),
                "router_bias": _stack(rb),
                "expert_gate_up_weights": _stack(egu),
                "expert_down_weights": _stack(edn),
                "expert_gate_up_weights_scale": _stack(egus),
                "expert_down_weights_scale": _stack(edns),
                "expert_gate_up_bias": _stack(egub),
                "expert_down_bias": _stack(edb),
                "swa_start_pos_ids": _stack(swa),
                "cos": cos0,
                "sin": sin0,
                "active_blocks_table": abt0,
                "attention_mask": mask0,
                "active_blocks_table_swa": abt0_swa,
                "kv_cache_update_idx": upd0,
                "pos_ids": pos0,
                "pos_ids_swa": pos0_swa,
                "rank_id": np.array([[rank_id]], dtype=np.uint32),
            }
            if _FP8_KV:
                arrays["k_scale"] = k_scale0
                arrays["v_scale"] = v_scale0
            if rank_id == _RANKS - 1:
                mg_shared = None
            return arrays

        def create_inputs(rank_id: int):
            if input_cache is None:
                arrays = generate_array_inputs(rank_id)
            else:
                arrays = input_cache.get_or_create(rank_id, lambda: generate_array_inputs(rank_id))

            result = {
                **arrays,
                "tp_replica_group": tp_group,
                "ep_replica_group": ep_group,
                "num_layers": num_layers,
                "tp_size": _TP,
                "ep_size": _RANKS,
                "B_attn": B_attn,
                "S_tkg": _S_TKG,
                "top_k": _TOP_K,
                "eps": _EPS,
                "hidden_actual": _H_ACTUAL,
                "softmax_scale": softmax_scale,
                "gate_clamp_upper_limit": _GATE_CLAMP_UPPER,
                "up_clamp_upper_limit": _UP_CLAMP_UPPER,
                "up_clamp_lower_limit": _UP_CLAMP_LOWER,
            }
            if _FP8_KV:
                # The kernel receives an explicit softmax scale, so it must
                # include the inverse K quantization scale. Read the scale from
                # `arrays` so cache hits follow the exact same path as misses.
                k_scale_scalar = float(np.asarray(arrays["k_scale"]).reshape(-1)[0])
                result["softmax_scale"] = softmax_scale / k_scale_scalar
            if _KV_UPDATE:
                # Aliasing: the kernel writes K/V in-place and returns them; the ".must_alias_input"
                # suffix tells the harness to alias those outputs onto these input buffers (the
                # kernel is called with the suffix stripped). The golden compares the post-update
                # caches, so they become validated outputs (output_keys below).
                result["K_cache.must_alias_input"] = result.pop("K_cache")
                result["V_cache.must_alias_input"] = result.pop("V_cache")
            return result

        # Perf/profiling mode: skip the expensive golden (stub ref = instant) and
        # accept-all validation, so the kernel still compiles + runs on device +
        # profiles without the ~40-min golden pass. Correctness is NOT checked here.
        if _SKIP_GOLDEN:
            torch_ref = make_stub_ref()
            comparator = _passthrough_comparator
        else:
            torch_ref = make_golden_ref(tp_group, ep_group, _TP, _RANKS, num_layers)
            comparator = _cosine_comparator
            # Prime the per-replica out_full cache in THIS (parent) process so the
            # ranks SimDistRunner forks inherit it copy-on-write (DP forwards total
            # instead of one per rank). Skip in compile-only/trace-only, where the
            # framework never generates the golden — priming would waste the compute.
            _is_compile_only = getattr(test_manager, "trace_mode", None) in (TraceMode.CompileOnly, TraceMode.TraceOnly)
            if not _is_compile_only:
                torch_ref.prime(create_inputs)

        CollectiveUnitTestFramework(
            test_manager=test_manager,
            kernel_entry=gpt_oss_decode_mega_kernel,
            torch_ref=torch_ref,
            per_rank_input_generator=create_inputs,
            collective_ranks=_RANKS,
        ).run_test(
            test_config=None,
            compiler_args=CompilerArgs(
                logical_nc_config=logical_nc_config,
                platform_target=platform_target,
                nki_compilation_mode=NKICompilationMode.tracer,
                additional_cmd_args=(
                    ["--enable-ocp-compliant-scale-computation"] + os.environ.get("MEGA_EXTRA_CC_ARGS", "").split()
                ),
            ),
            output_keys=(["out", "K_cache", "V_cache"] if _KV_UPDATE else ["out"]),
            rtol=7e-2,
            atol=1e-2,
            custom_comparator=comparator,  # cosine+relL2 (or accept-all if skip-golden)
            inference_args=InferenceArgs(
                collective_ranks=_RANKS,
                enable_determinism_check=False,
                profile_all_ranks=_env_enabled("VLLM_NEURON_MEGA_PROFILE_ALL_RANKS"),
                env_vars=_WORKER_ENV or None,
            ),
            profile_only=_SKIP_GOLDEN,
            input_artifacts_directory=_REUSE_INPUT_ARTIFACTS or None,
        )


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s", "-x"])
