# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""MXFP8 matmul input method microbenchmarks.

Compares different input preparation methods across representative
matrix shapes to measure their relative performance:

1. Prequantized MXFP8 swizzled (both LHS/RHS pre-quantized + swizzled)
2. Preswizzled BF16 (both LHS/RHS swizzled BF16, no spill reload)
3. DMA gather transpose (unswizzled BF16 with DGT tile_m=128)
4. PE swizzle 1x32 (unswizzled BF16 with PE swizzle, quant_scheme=1x32)
5. LHS BF16 wrapX PE swizzle + RHS wrapX prequantized (hybrid: LHS unswizzled
   wrapX PE swizzle, RHS pre-quantized MXFP8 wrapX-swizzled)
6. LHS BF16 1x32 PE swizzle + RHS 1x32 prequantized (hybrid: LHS unswizzled
   1x32 PE swizzle, RHS pre-quantized MXFP8 1x32-swizzled)
7. LHS BF16 DGT + RHS wrapX prequantized (hybrid: LHS unswizzled DMA
   gather-transpose, RHS pre-quantized MXFP8 wrapX-swizzled)

These tests are tagged with "model" to run in the model phase of the pipeline.
"""

import numpy as np
import pytest
from nkilib_src.nkilib.experimental.matmul_mxfp8 import matmul_mxfp8_generic_kernel
from nkilib_src.nkilib.experimental.matmul_mxfp8.matmul_mxfp8_torch import matmul_mxfp8_torch_ref

from test.integration.nkilib.experimental.matmul_mxfp8 import (
    config_helper,
    constants,
)
from test.integration.nkilib.experimental.matmul_mxfp8.test_matmul_mxfp8_generic_kernel import (
    _mxfp8_comparator,
    build_matmul_inputs,
    get_output_dtype,
)
from test.utils import common_dataclasses
from test.utils.pytest_test_metadata import pytest_marks, pytest_test_metadata
from test.utils.unit_test_framework import UnitTestFramework

# ============================================================================
# Benchmark shapes: (M, K, N, description)
# ============================================================================

_BENCHMARK_SHAPES = [
    (512, 512, 512, "SingleTile-512x512x512"),
    (4096, 4096, 4096, "Qwen235B-TP2-OProj"),
    (2048, 4096, 1536, "Qwen235B-TP2-MoE-GateUp-B2048"),
    (4096, 4096, 4608, "Qwen235B-TP2-FuseQKV"),
]


# ============================================================================
# Config generators for each input method
# ============================================================================


def _make_prequantized(shapes):
    """Method 1: Pre-quantized MXFP8 + swizzled, scale packing, no spill reload."""
    configs = []
    for M, K, N, desc in shapes:
        if K < 512:
            continue
        conf = config_helper.TestConfig(
            M=M,
            K=K,
            N=N,
            description=f"{desc} [prequantized]",
            run_with_lnc2=None,
            enable_scale_packing=True,
            output_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_dtype=constants.MatrixPrecision.MXFP8,
            rhs_dtype=constants.MatrixPrecision.MXFP8,
            lhs_is_swizzled=True,
            rhs_is_swizzled=True,
            spill_reload=False,
        )
        configs += conf.autoGenerateDefault()
    return configs


def _make_preswizzled(shapes):
    """Method 2: Preswizzled BF16, no scale packing, no spill reload."""
    configs = []
    for M, K, N, desc in shapes:
        conf = config_helper.TestConfig(
            M=M,
            K=K,
            N=N,
            description=f"{desc} [preswizzled]",
            run_with_lnc2=None,
            enable_scale_packing=False,
            output_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_dtype=constants.MatrixPrecision.BFLOAT16,
            rhs_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_is_swizzled=True,
            rhs_is_swizzled=True,
            spill_reload=False,
        )
        configs += conf.autoGenerateDefault()
    return configs


def _make_dma_gather_transpose(shapes):
    """Method 3: Unswizzled BF16 with DMA gather transpose (DGT).

    DGT requires tile_m=128 and K divisible by 128.
    """
    configs = []
    for M, K, N, desc in shapes:
        if K % 128 != 0:
            continue
        conf = config_helper.TestConfig(
            M=M,
            K=K,
            N=N,
            description=f"{desc} [dgt]",
            run_with_lnc2=None,
            enable_scale_packing=False,
            output_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_dtype=constants.MatrixPrecision.BFLOAT16,
            rhs_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_is_swizzled=False,
            rhs_is_swizzled=False,
            tile_m=128,
            TILES_IN_LOAD_N=1,
            spill_reload=True,
        )
        configs += conf.autoGenerateDefault()
    return configs


def _make_pe_swizzle_1x32(shapes):
    """Method 4: Unswizzled BF16 with PE swizzle 1x32 quantization."""
    configs = []
    for M, K, N, desc in shapes:
        conf = config_helper.TestConfig(
            M=M,
            K=K,
            N=N,
            description=f"{desc} [pe-swizzle-1x32]",
            run_with_lnc2=None,
            enable_scale_packing=False,
            output_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_dtype=constants.MatrixPrecision.BFLOAT16,
            rhs_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_is_swizzled=False,
            rhs_is_swizzled=False,
            load_with_PE_swizzle=True,
            quant_scheme="1x32",
            spill_reload=False,
        )
        configs += conf.autoGenerateDefault()
    return configs


def _make_lhs_wrapx_pe_swizzle_rhs_wrapx_prequantized(shapes):
    """Method 5: LHS unswizzled BF16 wrapX PE swizzle + RHS pre-quantized wrapX MXFP8.

    LHS is loaded with the BF16 wrapX PE transpose; RHS is already quantized and
    swizzled in HBM using the wrapX layout. Both operands' K axis use the wrapX
    permutation, so their quantization groups line up.
    """
    configs = []
    for M, K, N, desc in shapes:
        if K < 512:
            continue
        conf = config_helper.TestConfig(
            M=M,
            K=K,
            N=N,
            description=f"{desc} [lhs-pe-wrapx-rhs-prequant]",
            run_with_lnc2=None,
            enable_scale_packing=True,
            output_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_dtype=constants.MatrixPrecision.BFLOAT16,
            rhs_dtype=constants.MatrixPrecision.MXFP8,
            lhs_is_swizzled=False,
            rhs_is_swizzled=True,
            load_with_PE_swizzle=True,
            quant_scheme="wrapX",
            spill_reload=False,
        )
        configs += conf.autoGenerateDefault()
    return configs


def _make_lhs_1x32_pe_swizzle_rhs_1x32_prequantized(shapes):
    """Method 6: LHS unswizzled BF16 1x32 PE swizzle + RHS pre-quantized 1x32 MXFP8.

    LHS is loaded with the FP32-reinterpret 1x32 PE transpose; RHS is already
    quantized and swizzled in HBM using the 1x32 (contiguous-K) layout. Both
    operands' K axis use the 1x32 permutation, so their quantization groups
    line up.
    """
    configs = []
    for M, K, N, desc in shapes:
        if K < 512:
            continue
        conf = config_helper.TestConfig(
            M=M,
            K=K,
            N=N,
            description=f"{desc} [lhs-pe-1x32-rhs-prequant-1x32]",
            run_with_lnc2=None,
            enable_scale_packing=True,
            output_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_dtype=constants.MatrixPrecision.BFLOAT16,
            rhs_dtype=constants.MatrixPrecision.MXFP8,
            lhs_is_swizzled=False,
            rhs_is_swizzled=True,
            load_with_PE_swizzle=True,
            quant_scheme="1x32",
            spill_reload=False,
        )
        configs += conf.autoGenerateDefault()
    return configs


def _make_lhs_dgt_rhs_wrapx_prequantized(shapes):
    """Method 7: LHS unswizzled BF16 DGT + RHS pre-quantized wrapX MXFP8.

    LHS is loaded with the hardware DMA gather-transpose (wrapX layout, tile_m=128);
    RHS is already quantized and swizzled in HBM using the wrapX layout. DGT only
    produces the wrapX permutation, so both operands' K axis line up.
    """
    configs = []
    for M, K, N, desc in shapes:
        if K < 512 or K % 128 != 0:
            continue
        conf = config_helper.TestConfig(
            M=M,
            K=K,
            N=N,
            description=f"{desc} [lhs-dgt-rhs-prequant]",
            run_with_lnc2=None,
            enable_scale_packing=True,
            output_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_dtype=constants.MatrixPrecision.BFLOAT16,
            rhs_dtype=constants.MatrixPrecision.MXFP8,
            lhs_is_swizzled=False,
            rhs_is_swizzled=True,
            tile_m=128,
            TILES_IN_LOAD_N=1,
            quant_scheme="wrapX",
            spill_reload=False,
        )
        configs += conf.autoGenerateDefault()
    return configs


# ============================================================================
# Generate all configs
# ============================================================================

GRID_PREQUANTIZED = _make_prequantized(_BENCHMARK_SHAPES)
GRID_PRESWIZZLED = _make_preswizzled(_BENCHMARK_SHAPES)
GRID_DGT = _make_dma_gather_transpose(_BENCHMARK_SHAPES)
GRID_PE_SWIZZLE_1X32 = _make_pe_swizzle_1x32(_BENCHMARK_SHAPES)
GRID_LHS_WRAPX_PE_RHS_WRAPX_PREQUANT = _make_lhs_wrapx_pe_swizzle_rhs_wrapx_prequantized(_BENCHMARK_SHAPES)
GRID_LHS_1X32_PE_RHS_1X32_PREQUANT = _make_lhs_1x32_pe_swizzle_rhs_1x32_prequantized(_BENCHMARK_SHAPES)
GRID_LHS_DGT_RHS_WRAPX_PREQUANT = _make_lhs_dgt_rhs_wrapx_prequantized(_BENCHMARK_SHAPES)


# ============================================================================
# Test class
# ============================================================================


@pytest_test_metadata(name="Matmul Input Method Microbenchmarks", tags=["model"])
@pytest_marks(["generic_matmul_mxfp8_perf", "mx", "mxfp8", "model", "optimal"])
@pytest.mark.platforms(exclude=[common_dataclasses.Platforms.TRN1, common_dataclasses.Platforms.TRN2])
class TestMatmulMxfp8InputMethodMicrobenchmarks:
    """Microbenchmarks comparing matmul input preparation methods.

    Each test method exercises one input method across the benchmark shapes,
    measuring end-to-end matmul performance including data loading overhead.
    """

    def _run_test(self, test_manager, conf, platform_target):
        if not platform_target.is_trn3():
            pytest.skip("MX is only supported on TRN3.")

        compiler_args = common_dataclasses.CompilerArgs(
            logical_nc_config=2 if conf.run_with_lnc2 else 1,
            platform_target=platform_target,
        )

        test_manager.collector.set_kernel_params(conf.to_metrics_dict())
        output_dtype = get_output_dtype(conf)

        def input_generator(test_config):
            return build_matmul_inputs(conf)

        def output_tensors(kernel_input):
            return {"out": np.zeros((conf.M, conf.N), dtype=output_dtype)}

        framework = UnitTestFramework(
            test_manager=test_manager,
            kernel_entry=matmul_mxfp8_generic_kernel.matmul_mxfp8,
            torch_ref=matmul_mxfp8_torch_ref,
            kernel_input_generator=input_generator,
            output_tensor_descriptor=output_tensors,
        )
        framework.run_test(
            test_config=None,
            compiler_args=compiler_args,
            custom_comparator=_mxfp8_comparator(conf, output_dtype, False),
        )

    # --- Method 1: Prequantized MXFP8 ---

    @pytest.mark.parametrize("conf", GRID_PREQUANTIZED)
    def test_prequantized(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Method 2: Preswizzled BF16 ---

    @pytest.mark.parametrize("conf", GRID_PRESWIZZLED)
    def test_preswizzled(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Method 3: DMA Gather Transpose ---

    @pytest.mark.parametrize("conf", GRID_DGT)
    def test_dma_gather_transpose(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Method 4: PE Swizzle 1x32 ---

    @pytest.mark.parametrize("conf", GRID_PE_SWIZZLE_1X32)
    def test_pe_swizzle_1x32(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Method 5: LHS BF16 wrapX PE Swizzle + RHS wrapX Prequantized ---

    @pytest.mark.parametrize("conf", GRID_LHS_WRAPX_PE_RHS_WRAPX_PREQUANT)
    def test_lhs_wrapx_pe_swizzle_rhs_wrapx_prequantized(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Method 6: LHS BF16 1x32 PE Swizzle + RHS 1x32 Prequantized ---

    @pytest.mark.parametrize("conf", GRID_LHS_1X32_PE_RHS_1X32_PREQUANT)
    def test_lhs_1x32_pe_swizzle_rhs_1x32_prequantized(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Method 7: LHS BF16 DGT + RHS wrapX Prequantized ---

    @pytest.mark.parametrize("conf", GRID_LHS_DGT_RHS_WRAPX_PREQUANT)
    def test_lhs_dgt_rhs_wrapx_prequantized(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)
