# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""MXFP8 matrix multiplication kernel tests for multiple model configurations.

Tests model shapes under three input configurations:
- Unswizzled BF16 (spill reload)
- Swizzled BF16 (spill reload, no scale packing)
- Pre-quantized MXFP8 swizzled (scale packing)
"""

import numpy as np
import pytest
from nkilib_src.nkilib.experimental.matmul_mxfp8 import matmul_mxfp8_generic_kernel
from nkilib_src.nkilib.experimental.matmul_mxfp8.matmul_mxfp8_torch import matmul_mxfp8_torch_ref

from test.integration.nkilib.experimental.matmul_mxfp8 import (
    config_helper,
    constants,
    model_config_reader,
)
from test.integration.nkilib.experimental.matmul_mxfp8.test_input_microbenchmarks import (
    _make_dma_gather_transpose,
    _make_lhs_1x32_pe_swizzle_rhs_1x32_prequantized,
    _make_lhs_dgt_rhs_wrapx_prequantized,
    _make_prequantized,
)
from test.integration.nkilib.experimental.matmul_mxfp8.test_matmul_mxfp8_generic_kernel import (
    _mxfp8_comparator,
    build_matmul_inputs,
    get_output_dtype,
)
from test.utils import common_dataclasses
from test.utils.pytest_test_metadata import pytest_marks, pytest_test_metadata
from test.utils.unit_test_framework import UnitTestFramework


def populate_tests(grid, auto_generate_default=False):
    """Populate test configurations from a grid of base configs."""
    res = []
    for conf in grid:
        if auto_generate_default:
            res += conf.autoGenerateDefault()
        else:
            res += conf.autoGenerateRandomSubset(3)
    return res


def _make_model_configs(base_configs, run_with_lnc2=None, enable_scale_packing=True, **overrides):
    """Create test configs from model shapes with overrides applied BEFORE autoGenerateDefault."""
    base_configs = _exclude_core_attention(base_configs)
    output_dtype = overrides.pop('output_dtype', constants.MatrixPrecision.BFLOAT16)
    configs = []
    for base in base_configs:
        conf = config_helper.TestConfig(
            M=base.M,
            K=base.K,
            N=base.N,
            description=base.description,
            run_with_lnc2=run_with_lnc2,
            enable_scale_packing=enable_scale_packing,
            output_dtype=output_dtype,
            **overrides,
        )
        configs.append(conf)
    return populate_tests(configs, auto_generate_default=True)


def _make_unswizzled_bf16(base_configs):
    """Unswizzled BF16 (DGT mode) with spill reload.

    DGT requires tile_m=128. tile_k is forced to 512 by auto_generate_default
    (kernel handles K < 512 as remainder). TILES_IN_LOAD_M is auto-generated.

    Known issue: K < tile_k with LNC2 and large N produces incorrect results
    due to a DGT remainder + LNC2 interaction bug. Skip M=512,K=384,N=4096.
    """
    base_configs = _exclude_core_attention(base_configs)
    configs = []
    for base in base_configs:
        # Skip known LNC2 + DGT K-remainder bug (M=512, K=384, N=4096)
        # TODO fix bug and remove skip
        if base.M == 512 and base.K == 384 and base.N == 4096:
            continue
        # Skip known DGT validation failures for large square shapes with N=4608 or N=4096
        # TODO fix bug and remove skip
        if base.M == 4096 and base.K == 4096 and base.N in (4096, 4608):
            continue
        # DGT requires K divisible by 128
        if base.K % 128 != 0:
            continue
        conf = config_helper.TestConfig(
            M=base.M,
            K=base.K,
            N=base.N,
            description=base.description,
            run_with_lnc2=None,
            enable_scale_packing=False,
            output_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_dtype=constants.MatrixPrecision.BFLOAT16,
            rhs_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_is_swizzled=False,
            rhs_is_swizzled=False,
            tile_m=128,
            TILES_IN_LOAD_N=1,
            spill_reload=True,
        )
        configs.append(conf)
    return populate_tests(configs, auto_generate_default=True)


def _make_swizzled_bf16_spill_reload(base_configs):
    """Swizzled BF16 with spill reload, no scale packing."""
    return _make_model_configs(
        base_configs,
        lhs_dtype=constants.MatrixPrecision.BFLOAT16,
        rhs_dtype=constants.MatrixPrecision.BFLOAT16,
        lhs_is_swizzled=True,
        rhs_is_swizzled=True,
        spill_reload=True,
        enable_scale_packing=False,
    )


def _make_prequantized_swizzled(base_configs):
    """Pre-quantized MXFP8 + swizzled, scale packing, no spill reload. Skip K<512."""
    return [
        c
        for c in _make_model_configs(
            base_configs,
            lhs_dtype=constants.MatrixPrecision.MXFP8,
            rhs_dtype=constants.MatrixPrecision.MXFP8,
            lhs_is_swizzled=True,
            rhs_is_swizzled=True,
            spill_reload=False,
            enable_scale_packing=True,
        )
        if c.K >= 512
    ]


def _make_swizzled_bf16_no_scale_packing(base_configs):
    """Swizzled BF16, no scale packing, no spill reload."""
    return _make_model_configs(
        base_configs,
        lhs_dtype=constants.MatrixPrecision.BFLOAT16,
        rhs_dtype=constants.MatrixPrecision.BFLOAT16,
        lhs_is_swizzled=True,
        rhs_is_swizzled=True,
        spill_reload=False,
        enable_scale_packing=False,
    )


def _make_swizzled_bf16_scale_packing(base_configs):
    """Swizzled BF16, scale packing enabled, no spill reload."""
    return _make_model_configs(
        base_configs,
        lhs_dtype=constants.MatrixPrecision.BFLOAT16,
        rhs_dtype=constants.MatrixPrecision.BFLOAT16,
        lhs_is_swizzled=True,
        rhs_is_swizzled=True,
        spill_reload=False,
        enable_scale_packing=True,
    )


def _make_swizzled_bf16_scale_packing_spill_reload(base_configs):
    """Swizzled BF16, BOTH scale packing and spill reload."""
    return _make_model_configs(
        base_configs,
        lhs_dtype=constants.MatrixPrecision.BFLOAT16,
        rhs_dtype=constants.MatrixPrecision.BFLOAT16,
        lhs_is_swizzled=True,
        rhs_is_swizzled=True,
        spill_reload=True,
        enable_scale_packing=True,
    )


def _exclude_core_attention(configs):
    """Filter out per-head core attention shapes (QK^T, Attn*V, dScores, dV, dQ, dK)."""
    return [c for c in configs if "Attn-" not in c.description]


# --- Qwen3-8B TP1 ---
GRID_QWEN3_8B_TP1_UNSWIZZLED_BF16 = _make_unswizzled_bf16(model_config_reader.qwen3_8b_tp1)
GRID_QWEN3_8B_TP1_SWIZZLED_BF16_SPILL_RELOAD = _make_swizzled_bf16_spill_reload(model_config_reader.qwen3_8b_tp1)
GRID_QWEN3_8B_TP1_PREQUANTIZED_SWIZZLED = _make_prequantized_swizzled(model_config_reader.qwen3_8b_tp1)

# --- Qwen3-8B TP4 (original) ---
GRID_QWEN3_8B_TP4_UNSWIZZLED_BF16 = _make_unswizzled_bf16(model_config_reader.qwen3_8b_tp4)
GRID_QWEN3_8B_TP4_SWIZZLED_BF16_NO_SCALE_PACKING = _make_swizzled_bf16_no_scale_packing(
    model_config_reader.qwen3_8b_tp4
)
GRID_QWEN3_8B_TP4_SWIZZLED_BF16_SCALE_PACKING = _make_swizzled_bf16_scale_packing(model_config_reader.qwen3_8b_tp4)
GRID_QWEN3_8B_TP4_SWIZZLED_BF16_SPILL_RELOAD = _make_swizzled_bf16_spill_reload(model_config_reader.qwen3_8b_tp4)
GRID_QWEN3_8B_TP4_SWIZZLED_BF16_SCALE_PACKING_SPILL_RELOAD = _make_swizzled_bf16_scale_packing_spill_reload(
    model_config_reader.qwen3_8b_tp4
)
GRID_QWEN3_8B_TP4_PREQUANTIZED_SWIZZLED = _make_prequantized_swizzled(model_config_reader.qwen3_8b_tp4)

# --- Qwen3-32B TP1 ---
GRID_QWEN3_32B_TP1_UNSWIZZLED_BF16 = _make_unswizzled_bf16(model_config_reader.qwen3_32b_tp1)
GRID_QWEN3_32B_TP1_SWIZZLED_BF16_SPILL_RELOAD = _make_swizzled_bf16_spill_reload(model_config_reader.qwen3_32b_tp1)
GRID_QWEN3_32B_TP1_PREQUANTIZED_SWIZZLED = _make_prequantized_swizzled(model_config_reader.qwen3_32b_tp1)

# --- Qwen3-32B TP4 ---
GRID_QWEN3_32B_TP4_UNSWIZZLED_BF16 = _make_unswizzled_bf16(model_config_reader.qwen3_32b_tp4)
GRID_QWEN3_32B_TP4_SWIZZLED_BF16_SPILL_RELOAD = _make_swizzled_bf16_spill_reload(model_config_reader.qwen3_32b_tp4)
GRID_QWEN3_32B_TP4_PREQUANTIZED_SWIZZLED = _make_prequantized_swizzled(model_config_reader.qwen3_32b_tp4)

# --- Qwen3-235B TP2 (MoE) ---
GRID_QWEN3_235B_TP2_UNSWIZZLED_BF16 = _make_unswizzled_bf16(model_config_reader.qwen3_235b_tp2)
GRID_QWEN3_235B_TP2_SWIZZLED_BF16_SPILL_RELOAD = _make_swizzled_bf16_spill_reload(model_config_reader.qwen3_235b_tp2)
GRID_QWEN3_235B_TP2_PREQUANTIZED_SWIZZLED = _make_prequantized_swizzled(model_config_reader.qwen3_235b_tp2)

# --- Qwen3-235B TP1 (MoE) ---
GRID_QWEN3_235B_TP1_UNSWIZZLED_BF16 = _make_unswizzled_bf16(model_config_reader.qwen3_235b_tp1)
GRID_QWEN3_235B_TP1_SWIZZLED_BF16_SPILL_RELOAD = _make_swizzled_bf16_spill_reload(model_config_reader.qwen3_235b_tp1)
GRID_QWEN3_235B_TP1_PREQUANTIZED_SWIZZLED = _make_prequantized_swizzled(model_config_reader.qwen3_235b_tp1)

# --- GPT-OSS-20B TP2 (MoE) ---
GRID_GPT_OSS_20B_TP2_UNSWIZZLED_BF16 = _make_unswizzled_bf16(model_config_reader.gpt_oss_20b_tp2)
GRID_GPT_OSS_20B_TP2_SWIZZLED_BF16_SPILL_RELOAD = _make_swizzled_bf16_spill_reload(model_config_reader.gpt_oss_20b_tp2)
GRID_GPT_OSS_20B_TP2_PREQUANTIZED_SWIZZLED = _make_prequantized_swizzled(model_config_reader.gpt_oss_20b_tp2)

# --- Qwen3-235B QKV + OProj Ablation (TP1 + TP2, four input methods) ---
_QWEN3_235B_PROJ_SHAPES = [
    (c.M, c.K, c.N, c.description)
    for c in model_config_reader.qwen3_235b_tp1 + model_config_reader.qwen3_235b_tp2
    if "FuseQKV" in c.description or "OProj" in c.description
]

GRID_QWEN_PROJ_DGT = _make_dma_gather_transpose(_QWEN3_235B_PROJ_SHAPES)
GRID_QWEN_PROJ_PREQUANTIZED = _make_prequantized(_QWEN3_235B_PROJ_SHAPES)
GRID_QWEN_PROJ_LHS_DGT_RHS_PREQUANT = _make_lhs_dgt_rhs_wrapx_prequantized(_QWEN3_235B_PROJ_SHAPES)
GRID_QWEN_PROJ_LHS_PE_1X32_RHS_PREQUANT_1X32 = _make_lhs_1x32_pe_swizzle_rhs_1x32_prequantized(_QWEN3_235B_PROJ_SHAPES)


@pytest_test_metadata(name="Generic Matmul Perf Benchmarks", tags=["model"])
@pytest_marks(["generic_matmul_mxfp8_perf", "mx", "mxfp8", "model", "optimal"])
@pytest.mark.platforms(exclude=[common_dataclasses.Platforms.TRN1, common_dataclasses.Platforms.TRN2])
class TestMatmulMxfp8ModelConfigs:
    """Model shape tests under different input configurations."""

    def _run_test(self, test_manager, conf, platform_target):
        if not platform_target.is_trn3():
            pytest.skip("MX is only supported on TRN3.")

        compiler_args = common_dataclasses.CompilerArgs(
            logical_nc_config=2 if conf.run_with_lnc2 else 1,
            platform_target=platform_target,
        )

        test_manager.collector.set_kernel_params(conf.to_metrics_dict())
        output_dtype = get_output_dtype(conf)

        def input_generator(test_config):
            return build_matmul_inputs(conf)

        def output_tensors(kernel_input):
            return {"out": np.zeros((conf.M, conf.N), dtype=output_dtype)}

        framework = UnitTestFramework(
            test_manager=test_manager,
            kernel_entry=matmul_mxfp8_generic_kernel.matmul_mxfp8,
            torch_ref=matmul_mxfp8_torch_ref,
            kernel_input_generator=input_generator,
            output_tensor_descriptor=output_tensors,
        )
        framework.run_test(
            test_config=None,
            compiler_args=compiler_args,
            custom_comparator=_mxfp8_comparator(conf, output_dtype, False),
        )

    # --- Qwen3-8B TP1 ---

    @pytest.mark.parametrize("conf", GRID_QWEN3_8B_TP1_UNSWIZZLED_BF16)
    def test_qwen3_8b_tp1_unswizzled_bf16(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_8B_TP1_SWIZZLED_BF16_SPILL_RELOAD)
    def test_qwen3_8b_tp1_swizzled_bf16_spill_reload(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_8B_TP1_PREQUANTIZED_SWIZZLED)
    def test_qwen3_8b_tp1_prequantized_swizzled(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Qwen3-8B TP4 ---

    @pytest.mark.parametrize("conf", GRID_QWEN3_8B_TP4_UNSWIZZLED_BF16)
    def test_qwen3_8b_tp4_unswizzled_bf16(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_8B_TP4_SWIZZLED_BF16_NO_SCALE_PACKING)
    def test_qwen3_8b_tp4_swizzled_bf16_no_scale_packing(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_8B_TP4_SWIZZLED_BF16_SCALE_PACKING)
    def test_qwen3_8b_tp4_swizzled_bf16_scale_packing(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_8B_TP4_SWIZZLED_BF16_SPILL_RELOAD)
    def test_qwen3_8b_tp4_swizzled_bf16_spill_reload(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_8B_TP4_SWIZZLED_BF16_SCALE_PACKING_SPILL_RELOAD)
    def test_qwen3_8b_tp4_swizzled_bf16_scale_packing_spill_reload(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_8B_TP4_PREQUANTIZED_SWIZZLED)
    def test_qwen3_8b_tp4_prequantized_swizzled(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Qwen3-32B TP1 ---

    @pytest.mark.parametrize("conf", GRID_QWEN3_32B_TP1_UNSWIZZLED_BF16)
    def test_qwen3_32b_tp1_unswizzled_bf16(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_32B_TP1_SWIZZLED_BF16_SPILL_RELOAD)
    def test_qwen3_32b_tp1_swizzled_bf16_spill_reload(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_32B_TP1_PREQUANTIZED_SWIZZLED)
    def test_qwen3_32b_tp1_prequantized_swizzled(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Qwen3-32B TP4 ---

    @pytest.mark.parametrize("conf", GRID_QWEN3_32B_TP4_UNSWIZZLED_BF16)
    def test_qwen3_32b_tp4_unswizzled_bf16(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_32B_TP4_SWIZZLED_BF16_SPILL_RELOAD)
    def test_qwen3_32b_tp4_swizzled_bf16_spill_reload(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_32B_TP4_PREQUANTIZED_SWIZZLED)
    def test_qwen3_32b_tp4_prequantized_swizzled(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Qwen3-235B TP2 ---

    @pytest.mark.parametrize("conf", GRID_QWEN3_235B_TP2_UNSWIZZLED_BF16)
    def test_qwen3_235b_tp2_unswizzled_bf16(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_235B_TP2_SWIZZLED_BF16_SPILL_RELOAD)
    def test_qwen3_235b_tp2_swizzled_bf16_spill_reload(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_235B_TP2_PREQUANTIZED_SWIZZLED)
    def test_qwen3_235b_tp2_prequantized_swizzled(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Qwen3-235B TP1 ---

    @pytest.mark.parametrize("conf", GRID_QWEN3_235B_TP1_UNSWIZZLED_BF16)
    def test_qwen3_235b_tp1_unswizzled_bf16(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_235B_TP1_SWIZZLED_BF16_SPILL_RELOAD)
    def test_qwen3_235b_tp1_swizzled_bf16_spill_reload(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN3_235B_TP1_PREQUANTIZED_SWIZZLED)
    def test_qwen3_235b_tp1_prequantized_swizzled(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- GPT-OSS-20B TP2 ---

    @pytest.mark.parametrize("conf", GRID_GPT_OSS_20B_TP2_UNSWIZZLED_BF16)
    def test_gpt_oss_20b_tp2_unswizzled_bf16(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_GPT_OSS_20B_TP2_SWIZZLED_BF16_SPILL_RELOAD)
    def test_gpt_oss_20b_tp2_swizzled_bf16_spill_reload(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_GPT_OSS_20B_TP2_PREQUANTIZED_SWIZZLED)
    def test_gpt_oss_20b_tp2_prequantized_swizzled(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    # --- Qwen3-235B QKV + OProj Ablation (TP1 + TP2, four input methods) ---

    @pytest.mark.parametrize("conf", GRID_QWEN_PROJ_DGT)
    def test_qwen_proj_dgt(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN_PROJ_PREQUANTIZED)
    def test_qwen_proj_prequantized(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN_PROJ_LHS_DGT_RHS_PREQUANT)
    def test_qwen_proj_lhs_dgt_rhs_prequantized(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_QWEN_PROJ_LHS_PE_1X32_RHS_PREQUANT_1X32)
    def test_qwen_proj_lhs_pe_1x32_rhs_prequantized_1x32(self, test_manager, conf, platform_target):
        self._run_test(test_manager, conf, platform_target)
